### ISSUE TITLE
Crashreport with my Modpack

### ISSUE THREAD

**Issue by lebagvondouche** [spoorn/sodium-forge#1]
### Reproduction Steps
The client crashes together with other mods, works fine with just the Sodium mod installed but not with my modpack. I´m really bad at troubleshooting but thought I´ll let you know about this.

### Crash Report File
https://gist.github.com/haeihaiehaei/148f5d1540949d269c60fd1be1249578

Modlist:
https://gist.github.com/haeihaiehaei/525a4148a43c15ff27206504f1ca58b1

**Comment by spoorn** [comment]
It may be conflicting with the Performant mod, though I can't verify as Performant is closed-source.  

Could you try removing Performant?  It's known to cause issues with complex Mob AI as well

**Comment by lebagvondouche** [comment]
Working after Performant was removed, thanks!
