### ISSUE TITLE
Crash with Quark Glass

### ISSUE THREAD

**Issue by argenisRO** [spoorn/sodium-forge#100]
### Reproduction Steps
- Install Quark alongside Sodium-Forge
- Enter world in creative (or survival with JEI installed)
- Click on decorative items
- Scroll down until you crash (If JEI is installed, just type '@quark' in the search box and scroll through the pages until you crash)

### Crash Report File
[https://mclo.gs/7onqXPL](https://mclo.gs/7onqXPL)

### Mods list
- AutoRegLib [1.6]
- Sodium-Forge [2.9.5]
- Quark [r2.4]

### Additional Information
It seems to be an issue with the new glass items quark adds. 
I discovered this bug while playing a modpack (Seaopolis) and I just scrolled through all the items on the JEI.

**Comment by evanbones** [comment]
Can confirm, I have the same crash. Downgrading to 2.9.4 fixes it

**Comment by spoorn** [comment]
Please reopen/comment if it happens after the latest version.  I can't reproduce this anymore
