### ISSUE TITLE
Texture issues with Tetra after Sodium-Forge v2.9.5

### ISSUE THREAD

**Issue by Inqie** [spoorn/sodium-forge#103]
**Expected:**
As with Sodium-Forge v2.9.4, textures of Tetra modular tools should appear coloured like image below.
![Screenshot 2021-07-25 013842](https://user-images.githubusercontent.com/12848718/126874519-00bd67eb-687e-45ab-b93e-0f7774ff173e.png)

**Actual Behaviour:**
Sodium-Forge v2.9.5 and later produce grayscale textures with Tetra's modular tools. 
![Screenshot 2021-07-25 013532](https://user-images.githubusercontent.com/12848718/126874587-4b33ed88-061a-4767-966e-e4c22234e7a1.png)

**Reproduction:**
Make any custom tool in a Tetra workbench and check if the texture matches the materials used. 

**System Info:**
Minecraft Version: 1.16.5
Forge Version: 36.2.0
Sodium-Forge Version: 2.9.5
Tetra Version: 3.12.0
Java Version: 11.0.11 64bit
CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics
GPU: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2

**Comment by Pannoniae** [comment]
The problem is in MixinItemRenderer.
