### ISSUE TITLE
Silent Gear tools and Culinary Construct sandwiches are colorless

### ISSUE THREAD

**Issue by WenXin20** [spoorn/sodium-forge#104]
### Expected Behavior
- The dynamic tools from Silent Gear and the sandwiches from Culinary Construct should be colored correctly.

### Actual Behavior
- The tools and the sandwich layers are colored white instead of their appropriate colors.
- Downgrading back to v2.9.4 fixes this.

### Reproduction Steps

1. Craft a Silent Gear tool with a blueprint
2. Observe
3. Craft a sandwich using the sandwich station block
4. Observe

### Attachments
v2.9.5+
![2021-07-23_23 29 45](https://user-images.githubusercontent.com/12000593/126857767-475f20d5-6e24-4474-b13d-21b7e019f212.png)

v2.9.4
![2021-07-24_14 12 41](https://user-images.githubusercontent.com/12000593/126879015-29484271-e2c2-4348-a5ab-0f13240c4353.png)

(Ignore the axe, I forgot it was made from iron)

### Mods list
- [`Culinary Construct v4.0.0.6`](https://www.curseforge.com/minecraft/mc-mods/culinary-construct)
- [`Silent Gear v2.6.30`](https://www.curseforge.com/minecraft/mc-mods/silent-gear)

### System Information

- Java Version: [1.8.0_51]
- CPU: [4x AMD A12-9720P]
- GPU: [AMD Radeon R7]
- `Sodium Reforged v2.9.5 & v2.9.6`

**Comment by Pannoniae** [comment]
Same issue as #103

**Comment by WenXin20** [comment]
Ah, missed it because I typed this issue out yesterday and then posted it today after I made sure v2.9.4 was the version that worked.

**Comment by spoorn** [comment]
This is because Sodium only uses the registered ItemColor when rendering Item models, but mods like these 2 dynamically change the Item BakedModel's color.  This probably similar to https://github.com/spoorn/sodium-forge/issues/43, though I haven't gotten to fixing that one yet.

I'll fix this in the next release

**Comment by WenXin20** [comment]
Alright, thanks!
