### ISSUE TITLE
Sodium changes World Generation

### ISSUE THREAD

**Issue by Insane96** [spoorn/sodium-forge#105]
### Expected Behavior
The World gen should be the same as vanilla

### Actual Behavior
I have a ModPack with a few mods and decided to install Sodium, after goin into unloaded chunk there were chunk borders and the world had changed generation.

### Reproduction Steps
1. Create a new world without Sodium
2. Without moving look around to generate as many chunks as possible
3. Close the game, add Sodium and re-join the world
4. Go into unloaded chunks
5. Profit

### Attachments
![2021-07-25_07 44 06](https://user-images.githubusercontent.com/7185104/126889108-830bb784-c399-4ee3-b594-b72bf00bb3d2.png)
![2021-07-25_07 44 37](https://user-images.githubusercontent.com/7185104/126889109-2ac5eadf-1176-4bd9-a725-f69a818aa557.png)

### [Optional] Server/Client logs
[latest.log (after Sodium was added)](https://github.com/spoorn/sodium-forge/files/6873433/latest.log)

### Mods list
Tested with Sodium only

### System Information

- Java Version: 8u291
- CPU: AMD Ryzen 7 4800H
- GPU: Nvidia RTX 2060
- Sodium Reforged Version: 2.9.6 & 2.9.7
- Forge: 36.1.62 & 36.2.1

**Comment by spoorn** [comment]
Sodium contains some features of Lithium which optimize world gen.  You can add `mixin.gen.fast_layer_sampling=false` to the sodium config to use vanilla world gen.  Unfortunately, once world is generated, you can't regen it unless you delete the chunk region data from the Worlds folder
