### ISSUE TITLE
ArrayIndexOutOfBoundsException: crashing when trying to render

### ISSUE THREAD

**Issue by lepeli** [spoorn/sodium-forge#107]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

I just walked in my world and it crashed randomly but managed to create a crashdump file. Sadly I can't upload the world save as it is too big for me.

### Crash Report File
Please upload your crash report as a file to [GitHub Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and replace this text with a link to the uploaded report.

[crash-2021-07-25_11.34.35-client.txt](https://github.com/spoorn/sodium-forge/files/6873637/crash-2021-07-25_11.34.35-client.txt)

### [Optional] Server/Client logs
Sometimes a crash won't output a crash report file.  In your `logs/` folder, there should be a `latest.log` and/or `debug.log`.  You may include the **END** of this log showing any errors and a few surrounding lines of context.  Don't include the entire file as the first few lines of the log may contain some information of your file system. 

### Mods list
Include the list of mods loaded when the problem occurred.  If you have a crash report file, it should contain the list of mods running when the crash occurred.  

mods are in the crashreport

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.

**Comment by spoorn** [comment]
Do you have the latest.log?  The crash report isn't outputting the actual exception, it just wraps over it

**Comment by spoorn** [comment]
see https://github.com/spoorn/sodium-forge/issues/91
