### ISSUE TITLE
Mapping Mod stopped working.

### ISSUE THREAD

**Issue by TheSpicePhantom** [spoorn/sodium-forge#11]
### Expected Behavior
[TravellersMap](https://www.curseforge.com/minecraft/mc-mods/travellers-map) should map the area around me.

### Actual Behavior
Travellers Map stays blank.

### Reproduction Steps
Install latest Travellers Map, Sodium Reforged and forge.
Create a world and see yourself.

### Attachments
_none_

### System Information

- Java Version: AdoptOpenJDK 11.0.11.9 hotspot
- CPU: Intel Core i7-6700K (4c/8t) @4.01 Ghz
- GPU: GeForce GTX 1080 Ti

**Comment by Andyghandi** [comment]
Can confirm this same bug applies to FTB minimap and worldmap.

**Comment by R0M-A** [comment]
I've been using Journey Map for a while now and it works no problem.

**Comment by spoorn** [comment]
@Andyghandi FTB fixes this if you use the newer Alpha versions

**Comment by spoorn** [comment]
Closing this given that other map mods work.  You can follow up with Traveller's map for compatibility
