### ISSUE TITLE
Game Crashes When Opening Pocket Dimension

### ISSUE THREAD

**Issue by Divinos** [spoorn/sodium-forge#116]
Reproduction Steps

1. Install Sodium and Dimensional Pockets 2
2. Open pocket dimension
3. The game crashes

Crash Report File

https://gist.githubusercontent.com/natanfudge/7a05d2b9e46c45b4dc5e5c0b909b5292/raw/4d5945d6002089e342d37aa6ba59faa7fa7354f3/crash.txt

### Mods list

Cosmos Library 
Not Enough Crashes
Mana and Artifice
Just Enough Items 
Pocket Storage 
Health Overlay
AttributeFix
ToroHealth
Curios API
Patchouli                     
Journeymap                    
Citadel                       
Ore Excavation   
Artifacts                     
Inventory HUD+(Forge edition)
Occultism                     
Ice and Fire 
SodiumReforged
Just Enough Resources 
AppleSkin 
AutoFeederHelmet
ExpandAbility                 
Overloaded Armor Bar  
GeckoLib
Dimensional Pockets II

Additional Information

Not Enough Crashes said the mods involved in the crash were Sodium and Dimensional Pockets 2

**Comment by spoorn** [comment]
Is this consistently reproducible for you?  Even if you move your pocket dimension?  I can't reproduce this on my end

**Comment by spoorn** [comment]
see https://github.com/spoorn/sodium-forge/issues/91
