### ISSUE TITLE
Game fails to start correctly with SodiumReforged in folder.

### ISSUE THREAD

**Issue by YaGorl** [spoorn/sodium-forge#121]
I have a lot of mods in my mod folder, and before I start checking them all individually I wanted to see if anyone recognized any incompatible mods. I know this isn't the standard format, but I'm posting this just in case I can skip checking all of them. 
1. Copy mods into mods folder.
2. Start Minecraft Forge 36.1.32
3. Game crashes once deep scan of all mods has finished. 

https://mega.nz/file/4gESlThA#8jh3-mR_l23EteNt4iJU6D-qrtOArmawrhSLMxEiRpI
This is a zip with all the mods I use, if anyone recognizes any incompatible mods then please let me know. 

Edit: I ended up going through and narrowed it down, I've found that the mod performant-1.16.2-5-3.66 causes a crash when attempting to load up the game.
1. Put latest version of sodiumreforged and performant-1.16.2-5-3.66.
2. Launch Forge 36.1.32
3. Game crashes when deep scan is complete. 

Edit 2: I hadn't even realised that performant was in the folder, and now that I go check the main mod page, I see that it's incompatible. Sorry y'all.

**Comment by Hihzen85** [comment]
I've been having the exact same problem, I might need to find out what's causing this, I downloaded the recent version of forge, and right versions of every mod I have. And I have the right version of Minecraft. I think this mod has some compatibility issues with optifine or whatever mod's causing this problem. Please fix this. It's really important for me to install my favorite mods in 1.16.5 and not have lag.

**Comment by YaGorl** [comment]
Yeah optifine is incompatible with this mod. Check the CurseForge page, you should see all the incompatibilities on there. 
Honestly though, you shouldn't need optifine if you're using this.
> 
> 
> I've been having the exact same problem, I might need to find out what's causing this, I downloaded the recent version of forge, and right versions of every mod I have. And I have the right version of Minecraft. I think this mod has some compatibility issues with optifine or whatever mod's causing this problem. Please fix this. It's really important for me to install my favorite mods in 1.16.5 and not have lag.

**Comment by Hihzen85** [comment]
@YaGorl Okay, I kind of had a feeling about that, thanks for the confirmation. I did check forge for other incompatibilities, but I can't seem to find that list, do you know where to look or the incompatibles? I mean, the only thing I need Optifine for is shaders.

**Comment by YaGorl** [comment]
@Hihzen85 Well the only things on it are Optifine, Performant, and Immersive Portals, it's a little bit under the compatibility section of the CurseForge page
