### ISSUE TITLE
Crash when using the ritual system in Eidolon

### ISSUE THREAD

**Issue by alipali737** [spoorn/sodium-forge#122]
### Reproduction Steps
Crash when beginning the ritual process for the "crystallization ritual" in Eidolon

1. Place 2 item receptacles either side of the brazier
2. Place 1 Redstone dust in either receptacle
3. Place 1 Bonemeal in the brazier in the middle
4. Ignite the brazier with a flint + steel (Game crashes at this point)

### Crash Report File
Full crash report: https://pastebin.com/8LqMjuQG

### Mods list
Full mod list included at the end of the crash report found above. Too many to list overall (200+). The mods can also be found in the pack: https://www.curseforge.com/minecraft/modpacks/official-eclipse-pack

### Additional Information
Tried lowering particle quality + disabling particle culling but has no effect

**Comment by spoorn** [comment]
Upgrade sodium
