### ISSUE TITLE
Compat for Better Foliage?

### ISSUE THREAD

**Issue by JakeSublime** [spoorn/sodium-forge#123]
Im getting a crash on MC 1.16.5 with the latest versions of Sodium Forge and Better Foliage (+kotlin for forge).  There are other mods installed, but the crash report says specifically "Could not initialize class mods.betterfoliage.BetterFoliageMod" soo..

Just wanted to ask if this has been tested with better foliage. Thanks!

**Comment by spoorn** [comment]
dupe of https://github.com/spoorn/sodium-forge/issues/16
