### ISSUE TITLE
Entering nether cause client crash

### ISSUE THREAD

**Issue by ghost** [spoorn/sodium-forge#127]
Entering nether cause client crash, here I attached gist crash-log:
https://gist.github.com/ternsip/2b410a6918161be04157e21495164194
re-entering game gives pretty similar crash:
https://gist.github.com/ternsip/989aa468254347edcb46c808b36f872d
this could be due to portal frames

**Comment by spoorn** [comment]
see https://github.com/spoorn/sodium-forge/issues/91
