### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by emanuele246gi** [spoorn/sodium-forge#128]
### Reproduction Steps
As I understand, there is no exact steps to reproduce this, but it has to do with Immersive Engineering and Immersive Petroleum, it shows a bunch of duplicate object (just rendering, not real blocks) and then crashes

### Crash Report File
https://pastebin.com/QZbkpAPE

### Mods list
It is in the crash report

Sodium Reforged Version: Latest on 1.16.5
Forge Version: 36.2.2

**Comment by spoorn** [comment]
Fixed in https://github.com/spoorn/sodium-forge/commit/7c5fd2a10f10671cc0656d7206c999685a65998f
