### ISSUE TITLE
[2.1.5] Crash with Create's ponder features

### ISSUE THREAD

**Issue by Ritzumi** [spoorn/sodium-forge#13]
### Reproduction Steps

1. Create and join a new world
2. Go to Create's creative tab
3. Press 'w' to ponder on available components.
4. Ponder for a while and the see error.

### Crash Report File
https://gist.github.com/Ritzumi/5b0d4d0fc603338777ae7abacaf2f8e7

### Additional Information
None.

Thank you.

**Comment by pm065** [comment]
Can confirm, works for some like the Cogwheel but the Adjustable Repeater's one doesn't

**Comment by Inqie** [comment]
I also get this craash.
MC 1.16.5; Forge 36.1.31; Mod v2.1.5; Java 11.0.11; AMD Ryzen 9 5900HX; RTX 3070 Laptop

**Comment by spoorn** [comment]
Should be fixed in https://github.com/spoorn/sodium-forge/commit/08ad9edb8c18d5aa9490de321453b1fda7d6085b
