### ISSUE TITLE
optifine crashes when sodium loads (optifine in mods folder)

### ISSUE THREAD

**Issue by darthmendorian** [spoorn/sodium-forge#134]
optifine crashes when sodium loads (optifine in mods folder)

**Comment by evanbones** [comment]
Doesn't work with Optifine, and you shouldn't expect it to ever

**Comment by spoorn** [comment]
Sodium is incompatible with Optifine

**Comment by darthmendorian** [comment]
why tho?

**Comment by evanbones** [comment]
Optifine is closed source and makes many invasive changes to Minecraft's rendering engine, changes that conflict with Sodium's.
