### ISSUE TITLE
 Mixin apply failed sodium.mixins.json:gen.features.StructureFeatureMixin

### ISSUE THREAD

**Issue by NighthowlerStudios** [spoorn/sodium-forge#135]
Using a dev branch of Kaleidio's Battle Pack (an older version with some similar mods is available on curseforge, 3.4.9 recommended) Sodium Reforged crashes when applying structure mixins.  why is there optimization for this in a client side mod?  I'm confused.

[latest.log](https://github.com/spoorn/sodium-forge/files/6949950/latest.log)

**Comment by Pannoniae** [comment]
Performant is not too compatible.:(

**Comment by Kaleidio** [comment]
It's not caused by Performant.  Just tested without it.
