### ISSUE TITLE
Buzzier Bees honey pot renders incorrectly when Sodium-Forge is installed

### ISSUE THREAD

**Issue by pm065** [spoorn/sodium-forge#14]
First of all, thank you so much for putting Sodium-Forge on Curse. It works excellently, even having full compatibility with Create (EDIT: Didn't realise the ponder feature was broken ): ), the only issues I've found are one with Structure Gel (which I've reported to them) and this one with Buzzier Bees.

The honey pot, when filled with honey, renders strangely; it becomes transparent beyond the honey. This occurs on fancy and fast graphics. (Fabulous just causes the whole pot to disappear.)
![2021-06-13_15 19 06](https://user-images.githubusercontent.com/81559564/121811042-f2f1fc00-cc5a-11eb-96a0-8f21362f5f30.jpg)

Reproduction:
1. Place a BB Honey Pot
2. Fill it with honey
3. Profitn't

Details:
- Minecraft Version: 1.16.5 (Feels kind of weird that that isn't actually the latest anymore)
- Forge Version: 36.1.31
- Mod Version: 2.1.5
- Java Version: 14.0.2 64bit
- CPU: 8x Intel Core i7-10510U CPU 1.80 GHz ~2.3GHz
- GPU: NIVIDIA GeForce MX250 (I think that's the GPU? I couldn't see anything explicitly marked GPU.)

**Comment by spoorn** [comment]
This is due to culling the block faces that are not directly in view of the player.  Culling optimizes rendering by not even rendering pixels that are not in direct view.  Problem here is the honey is translucent so you can see through it

**Comment by KKotik** [comment]
![image](https://user-images.githubusercontent.com/45950781/122563541-fe736780-d04c-11eb-81b2-22077d6bd733.png)
Same with Create's nixie tubes.

**Comment by KKotik** [comment]
But only when they overlap in fov. 
![image](https://user-images.githubusercontent.com/45950781/122563680-26fb6180-d04d-11eb-8033-904b99ba4228.png)

**Comment by spoorn** [comment]
Should be fixed now if you turn on `Translucency Sorting` and turn off `Use Compact Vertex Format`

![img](https://i.imgur.com/XXO8Zj1.png)
