### ISSUE TITLE
Create moving contraptions invisible after latest update (Create 0.3.2d)

### ISSUE THREAD

**Issue by rigerc** [spoorn/sodium-forge#142]
### Expected Behavior
Moving contraptions should show up.

### Actual Behavior
Moving contraptions are invisible but functional.

All moving components are invisible (the moving parts of any Create block)

### Reproduction Steps
Example: attach a linear chassis to a mechanical bearing, activate it and it'll be invisible.

### Mods list
Had an Extensive modlist when I encountered this but removing Sodium Reforged fixed it. 

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: 8
- CPU: 3600x
- GPU: 3070
- Sodium Reforged Version: 2.9.10+rev.ea6353c

**Comment by FreeFull** [comment]
Seems like the workaround is to set the mipmap level to 1

**Comment by VinylObscura** [comment]
Same problem here, and unfortunately setting mipmap level to 1 doesn't work. Begging on my knees please fix this lol :(

**Comment by Fireflexor** [comment]
Same issue and the mipmap thing doesn't work. would appreciate a fix

**Comment by Fireflexor** [comment]
ok its an incompatibility with the flywheel version required to use create 0.3.2d not create itself as i expected. a fix is to rollback both of these mods for now and wait for a fix

**Comment by Pannoniae** [comment]
Please test if still invisible. I've tested it with 3 mods (Sodium, Create, Flywheel) and it seemed to work.

**Comment by MrReps** [comment]
> Please test if still invisible. I've tested it with 3 mods (Sodium, Create, Flywheel) and it seemed to work.

With the release 2f18d7470ae20573cf43b1f214ae7bde3f76ad60, Flywheel 0.2.3 and create 0.3.2d strucutre stay invisible. Maybe i didn't take the correct version of sodium or i wrongly build it

**Comment by ssateq** [comment]
> With the release [2f18d74](https://github.com/spoorn/sodium-forge/commit/2f18d7470ae20573cf43b1f214ae7bde3f76ad60), Flywheel 0.2.3 and create 0.3.2d strucutre stay invisible. Maybe i didn't take the correct version of sodium or i wrongly build it

The same for me.

**Comment by F0gboy** [comment]
Any news about this problem?

**Comment by emanuele246gi** [comment]
Idem :(

**Comment by FlameyFaucet** [comment]
They fixed it. Go check out FLywheel's page for the new version, and most of the issues should poof :D
Of course, sodium still needs to do something on their end. So everything may not be fine.

**Comment by MrReps** [comment]
Yep fully fixed noice :)
