### ISSUE TITLE
More GUI options

### ISSUE THREAD

**Issue by EAGBCD** [spoorn/sodium-forge#147]
**Is your feature request related to a problem? Please describe.**
The biggest GUI (4) is to small. Auto is to big. Before I installed sodium I had more options and was able to pick a favorable GUI scale. 

**Describe the solution you'd like**
Add options greater then 4. I think before I installed the mod there were 7 or 8. Not sure if thats vanilla or part of the modpack (Enigmatica 6) I am using.

**Describe alternatives you've considered**
Uninstall the mod.

Or uninstall adjust GUI reinstall and see if it stays. 

**Additional context**
Thanks for the mod it's great and I appreciate your hard work.

**Comment by Pannoniae** [comment]
I've implemented the vanilla logic (which has larger scales in 4k). Do you want anything else as well?:)

**Comment by EAGBCD** [comment]
Nope! If it works the same as before I installed sodium it will be perfect. I'm able to get what I want with that so I will be good. 

Actually my alternate solution of adjust GUI and then add sodium worked, I set it to 5, and then when I install sodium it stays on 5, I just can't touch it accidentally because then you can't get 5 back. 

Thanks for the great mod, and the responses on and fixing both of my issues. (FTB chunk explosions was my other) excited for the update to release. 

*Edit, well shit, I would love dynamic light and zoom from Optifine. Probably lower priority then fixing bugs and actual performance increases, and I don't miss those features too much really. Also gameplay mods add items and things in game you can do to get close to those abilities. But if they were here, I would use, enjoy, and appreciate them. 

Sorry to make more work if you decided to go for it, and thanks again, I couldn't play big 1.16 packs without this mod and your hard work.
