### ISSUE TITLE
Sodium mod stops FTB Chunks mod from protecting claimed chunks. 

### ISSUE THREAD

**Issue by EAGBCD** [spoorn/sodium-forge#148]
### Expected Behavior
1. Claim chunks using FTB chunks mod version 1605.3.1-build.41 (latest)
2. Have a creeper explode. 
3. No damage will be done to blocks or the world in the claimed chunks.

### Actual Behavior
1. Claim chunks
2. Blow up creeper in claimed chunks 
3. Blocks and world are blown up, even though the area is claimed. 

### Reproduction Steps
See above.

### Mods list
Eniigmatica 6 Modpack
https://www.curseforge.com/minecraft/modpacks/enigmatica6/files

### System Information

- Java Version: [Java 8 update 291 build 10] (Edit* I updated to Java 8 update 301 (the latest) and still had the problem)
- CPU: [3.1 GHz Intel Core i5]
- GPU: [Intel Iris Graphics 550 1536 MB]
- Sodium Reforged Version: [2.9.10]

I know it is this mod because I installed a fresh unchanged version of the modpack, created a world, claimed chunks, blew up creepers and had no damage. I then closed the game, added sodium mod, joined the same world I created, blew up creepers in my claimed chunks, and now they destroyed the environment. 

Thanks again for the mod and your help.

**Comment by Pannoniae** [comment]
Fixed in #155
