### ISSUE TITLE
No compatible with Better Biome Blend!!!

### ISSUE THREAD

**Issue by ghost** [spoorn/sodium-forge#149]
curseforge: https://www.curseforge.com/minecraft/mc-mods/better-biome-blend
Fabric version does not have this problem
![Vanilla UI](https://user-images.githubusercontent.com/85747337/129427523-a70a2965-b009-4de2-a7b1-6f1e27b31211.png)
![Sodium UI](https://user-images.githubusercontent.com/85747337/129427525-6348602f-d107-48e0-9757-b6f58eff0805.png)

**Comment by ghost** [comment]
I realize I used the wrong template, sorry
After all, I'm not familiar with English

**Comment by evanbones** [comment]
Won't ever work with biome blend most likely, Sodium overwrites most of its features

**Comment by ghost** [comment]
Well, I don't think I need it anymore

**Comment by ghost** [comment]
Thank you
