### ISSUE TITLE
Upgrade Aquatic's jelly torch renders incorrectly with Sodium-Reforged installed

### ISSUE THREAD

**Issue by Inqie** [spoorn/sodium-forge#15]
The effort to port not only Sodium but also Lithium and Phosphor to Forge is _greatly_ appreciated. 

With that said, small problem when using Upgrade Aquatic by TeamAbnormals:
Jelly Torches in all colours don't render their translucent pixels. These little torches are adorable, so I hope this can get fixed!

**Reproduction:**

1. Place Jelly Torch of any colour
2. Render issue

![14Jun2021](https://user-images.githubusercontent.com/12848718/121840314-1f6d4d00-cd1b-11eb-8e5e-af438378a678.png)

**System Info:**

Minecraft Version: 1.16.5
Forge Version: 36.1.31
Mod Version: 2.1.5
Java Version: 11.0.11 64bit
CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics
GPU: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2

**Comment by spoorn** [comment]
Should be fixed in https://github.com/spoorn/sodium-forge/commit/4f288b03ea4c8fcddf64ff3410086cae9ad4d9b0
