### ISSUE TITLE
Game crashes whilst loading all mods, exit code 0

### ISSUE THREAD

**Issue by flwerr** [spoorn/sodium-forge#150]
Whilst loading the mods upon starting the game, it crashes once it reaches loading this mod, removing sodium reforged fixes it but I would really like to use this mod.

### Crash Report File
no crash report created :?

### [Optional] Server/Client logs
https://pastebin.com/D3mhHZSj

### Mods list
https://imgur.com/a/TYPLuus

**Comment by Pannoniae** [comment]
Optifine is not compatible with Sodium. (TODO: we should maybe hard-crash in that case)

**Comment by flwerr** [comment]
> Optifine is not compatible with Sodium. (TODO: we should maybe hard-crash in that case)

Oh thank u ! I completely forgot I had optifine installed honestly
