### ISSUE TITLE
Crash with RFToolsBuilder

### ISSUE THREAD

**Issue by tuca1234567890** [spoorn/sodium-forge#153]
### Reproduction Steps
1. Make a game instance with Forge 36.2.0, Sodium Reforged 2.9.10, McJtyLib, RFToolsBase and RFToolsBuilder
2. Create a new world
3. Place the builder in the world

### Crash Report File
https://gist.github.com/tuca1234567890/52420343bdeb6fa954df60c951d61e62

### [Optional] Server/Client logs
https://gist.github.com/tuca1234567890/ebbf3853c1436260b2e27973dbf68c01 (latest.log)

### Mods list
forge-1.16.5-36.2.0-client.jar
sodium-forge-2.9.10+rev.ea6353c.jar                
forge-1.16.5-36.2.0-universal.jar                
mcjtylib-1.16-5.0.22.jar                            
rftoolsbase-1.16-2.0.10.jar                        
rftoolsbuilder-1.16-3.1.1.jar

**Comment by Pannoniae** [comment]
Does it happen without Sodium installed?

**Comment by tuca1234567890** [comment]
> Does it happen without Sodium installed?

Just tested it and yes. I think it's rftools' fault then, sorry.

**Comment by Pannoniae** [comment]
Thank you!<3

**Comment by Pannoniae** [comment]
BTW I think one of your RFTools mods are outdated. Try updating all of them.:)
