### ISSUE TITLE
Conflicts with Interactio Explosion Recipes

### ISSUE THREAD

**Issue by Kardane** [spoorn/sodium-forge#155]
### Expected Behavior
Interactio adds in-worlds recipes using explosives(TNT,Creepers).
Using examples from interactio github, 
exploding gold ingot and redstone dust gives gold nugget or redstone block.

### Actual Behavior
But when Sodium Reforged installed, TNT and Creeper just blew away ingredients.

### Reproduction Steps
Install Interactio and Sodium Reforged.
Make a datapack with interactio explosion recipes.
I used example from Interactio github >>https://github.com/MaxNeedsSnacks/Interactio/wiki/Examples-of-In-World-Recipes

1. Throw 1 redstone dust and 2 gold ingots
2. Ignite TNT or Creeper
3. Nothing happens. Item blew away.

### System Information

- Java Version: [Java 16.0.1]
- CPU: [Ryzen 7 2700 Eight-Core Processor 3.20 GHz]
- GPU: [Radeon RX580]
- Sodium Reforged Version: [sodium-forge-2.9.10+rev.ea6353c]

**Comment by Pannoniae** [comment]
The forge explosion event is not fired in our explosion mixin. Will fix.
