### ISSUE TITLE
Enigmatica 6 won't load if Sodium is in the modlist

### ISSUE THREAD

**Issue by EnderDrip** [spoorn/sodium-forge#160]
_Game should load properly._

_Loading screen freezes when the bar is almost full and he Mojang logo is almost invisible._

1. Install Sodium Reforged on Enigmatica 6 
2. Load the pack. 

### Attachments
![fa664enkcij71](https://user-images.githubusercontent.com/89584258/130957961-611607b7-41c2-440d-973b-236057faf69c.png)

### Mods list
Latest Enigmatica 6 build (0.5.11) + Sodium Reforged

### System Information
- Java Version: [1.8.0_291]
- CPU: [Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz]
- GPU: [NVIDIA GeForce GTX 1050]
- Sodium Reforged Version: [2.9.10]

**Comment by EnderDrip** [comment]
It's not a sodium problem, rather is the pack itself

**Comment by NielsPilgaard** [comment]
I can assure you Enigmatica 6 0.5.11 can start without Sodium Reforged :P
