### ISSUE TITLE
Appears To Break All Shaders

### ISSUE THREAD

**Issue by ghost** [spoorn/sodium-forge#18]
### Expected Behavior
My game should look nice and lovely with shaders applied.

### Actual Behavior
It looks like someone forced an AI to dream up a new pride flag:

![image](https://user-images.githubusercontent.com/24266948/121990283-d67fcc00-cde0-11eb-912a-834b0f6cfd81.png)
![image](https://user-images.githubusercontent.com/24266948/121990293-de3f7080-cde0-11eb-8c27-1a36e39766db.png)

### Reproduction Steps
I assume just have [my mods list](https://gist.github.com/Brittank88/d7b0e726322a364c8452f2b2fddfe78d) and try applying shaders with and without Sodium Reforged enabled.

### Extra Info
This happens across numerous shaderpacks, in fact, I am yet to find one that functions alongside this mod.

There's this line in the log when applying shaders, that only appears when this mod is enabled:
`[23:39:13] [Render thread/ERROR] [ne.op.sh.SMCLog/]: [Shaders] OpenGL error: 1282 (Invalid operation), program: shadow, at: blockEntityId`

### System Information
![image](https://user-images.githubusercontent.com/24266948/121990449-29f21a00-cde1-11eb-9775-d8640b58f096.png)

- Java Version: `AdoptOpenJDK 1.8.0_242 Hotspot`
- CPU: `AMD Ryzen 9 3900X 12-Core`
- GPU: `NVIDIA GeForce RTX 2070 SUPER`

**Comment by spoorn** [comment]
Sodium and Optifine are incompatible.  Both of them touch the same rendering pipeline code of vanilla minecraft, and currently, sodium does not have Shader support implemented.  There are currently no plans to add support for Shaders, nor compatibility with Optifine.

**Comment by ghost** [comment]
Ah, okay, fair enough.
