### ISSUE TITLE
Rendering issue with I&F myrmex resin glass

### ISSUE THREAD

**Issue by brisingraerowing** [spoorn/sodium-forge#19]
### Expected Behavior
Glass has border around edge

### Actual Behavior
Glass border makes Swastika.

### Reproduction Steps
Place down (or find) a 2x2 of Myrmex Resin Glass

### Attachments
![2021-06-15_19 45 04](https://user-images.githubusercontent.com/250409/122237791-9aef0b80-ce8d-11eb-89e5-738f36965985.png)

### System Information

- Java Version: 1.8.0_275 (AdoptOpenJDK)
- CPU: Intel Core i5-9400F
- GPU: NVIDIA GEFORCE GTX 1660

**Comment by spoorn** [comment]
Seems to be working for me now:

![image](https://i.imgur.com/YfxlW3V.png)
