### ISSUE TITLE
Mixin-Related Crash / Using sodium-mixins.properties?

### ISSUE THREAD

**Issue by ghost** [spoorn/sodium-forge#2]
### Reproduction Steps
The game crashes immediately on startup (during mixin registration, I believe). There are no steps except having the mod set that I do for this pack. __Here's the [mods list](https://gist.github.com/Brittank88/d71bf10398b3772857180ed0360a3251)__.

Yes, it has Optifine. If this means you can't do anything on your end, I totally get that, but please, __tell me how to operate `sodium-mixins.properties` because that information doesn't exist on the internet apparently__.

### Crash Report File
No crash report is generated (I believe the error occurs too early in the loading process) but __here is the excerpt from [latest.log](https://gist.github.com/Brittank88/f24cbd02942c06d58c22d7eaa7adf5e0)__.

### Additional Information
I believe I just need to disable the `features.options.MixinInGameHud` mixin, which I know can be achieved via the `sodium-mixins.properties` file. Problem is, there is absolutely NO documentation on this config. The wiki link doesn't work and the devs over at sodium-fabric have acknowledged it by doing exactly nothing to provide further information.

## Thanks for your time! <3

**Comment by ghost** [comment]
Note: After manually commenting out `"features.options.MixinInGameHud"` and `"features.options.MixinWorldRenderer"` in `sodium.mixins.json`, the crash stops occurring, and I am able to load into the main menu. I am not sure how much this restricts the mod's ability to actually do things though.

Doesn't matter anyways, because the game will freeze and crash in the background upon entering a world. __Here's [the crash report](https://gist.github.com/Brittank88/9049d0f2fb17c6e483d54a25c2ae074b) for that__.

**Comment by ghost** [comment]
Edited issue title, considering that whilst I am still curious about how to use `sodium-mixins.properties`, it seems like it won't prevent the game from crashing.

Does Optifine actually offer anything that this mod doesn't? I'd happily remove it if this pretty much fills in the gaps. It would actually be better, as this is on Curseforge and slightly easier to include in my pack.

**Comment by spoorn** [comment]
Sodium is definitely incompatible with **Optifine**, but from your second crash report, it looks like an incompatibility issue with **Immersive Portals** as well.  This was a known issue in the original Fabric version of Sodium.  I can take some time later to look into a possible fix, but for now Sodium is incompatible with both of those mods.

**Comment by ghost** [comment]
Totally understandable. I know that Optifine straight up yoinks the rendering pipeline so there's not much to be done there for compatibility.

Would still love to know how to disable mixins via the appropriate config.

Furthermore, the two mixins I disabled to make it work, how important are they? Seems like the second one I disabled could end up making sodium a lot less useful, bit that's just me guessing on the name of the mixin.

**Comment by spoorn** [comment]
These should be the config options for that .properties file: https://github.com/spoorn/sodium-forge/blob/1.16.x/dev/src/main/java/me/jellysquid/mods/sodium/common/config/SodiumConfig.java#L26

I rarely see these used though.  Don't think you can disable mixins from there.

As for those 2 mixins, they are not game breaking.

**Comment by ghost** [comment]
Oh my god, I saw that already but it was a version with only like 25% of what is here. Thank you very much. I'll definitely make use of it once the IP compat issue is fixed.

**Comment by ghost** [comment]
Considering that this is a forge port of a fabric mod, I don't know if you are willing to deviate from the development of the sodium version of the mod at all but... If that `sodium.mixins.json` file could be made configurable that would be amazing.

If you're saying you can't actually disable mixins from `sodium-mixins.properties`, it would be a much cleaner way to allow that to be possible. I understand that mixin registration occurs very early on in the loading process though, so I am not sure what limitations that places on this being possible. Maybe a piece of code to automatically disable those two mixins if Optifine is present could be added?

**Comment by spoorn** [comment]
Dug into a little more, you can disable mixins using `sodium-mixins.properties`  using the end of the package path of the class from "mixin", e.g. `mixin.gen.fast_island_noise=false`.

Are those the only 2 mixins that conflict with Optifine?  I can try testing it out myself later

**Comment by ghost** [comment]
After disabling those two mixins, I was able to load up my game. With either one disabled, my game crashes before the window even opens.

**Comment by ghost** [comment]
Okay so, currently, the limitation is that I could use `sodium-mixins.properties` to disable `mixin.features.options` entirely, but there's no way to disable the specific mixins that are present under that. It's only two of them that cause issues, not all 5 in [the folder](https://github.com/spoorn/sodium-forge/tree/1.16.x/dev/src/main/java/me/jellysquid/mods/sodium/mixin/features/options).

I can confirm however that adding `mixin.features.options = false` to `sodium-mixins.properties` does indeed allow the game to start up without crashing.

**Comment by ghost** [comment]
If you happen to identify a specific set of mixins causing the conflict with IP, would you mind letting me know so at least temporarily I can disable them to make the mods work together? It would allow me to continue pack testing with this mod included, meaning when I add new mods I can also see if they have compatibility with Sodium Reforged or not.

**Comment by spoorn** [comment]
I just noticed your crash log also shows you have Optifine.  Sodium is incompatible with Optifine.

Also, Immersive Portals for Forge is not being supported anymore: https://github.com/qouteall/ImmersivePortalsModForForge

As such, I won't have the bandwidth to work on compatibility for a non-maintained project
