### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ArgonGaming** [spoorn/sodium-forge#23]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Install Sodium Reforged for 1.16.5

### Crash Report File
Please upload your crash report as a file to [GitHub Gist](https://gist.github.com/) and replace this text with a link to the uploaded report.
https://pastebin.com/HfnCcQ0p

**Comment by spoorn** [comment]
Can you paste your list of mods?

**Comment by logwet** [comment]
It may help if you install [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge) to give more detailed crash info. But besides that a quick look through the crash log suggests that the problem is caused by a conflict with a Performant mixin. This mod is incompatible with performant, so try removing it and relaunching.

```java
Mixin apply failed sodium.mixins.json:gen.features.StructureFeatureMixin -> net.minecraft.world.gen.feature.structure.Structure: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/gen/feature/structure/Structure::biomeConditionalGetChunk with priority 1000 cannot inject into net/minecraft/world/gen/feature/structure/Structure::func_236388_a_(Lnet/minecraft/world/IWorldReader;Lnet/minecraft/world/gen/feature/structure/StructureManager;Lnet/minecraft/util/math/BlockPos;IZJLnet/minecraft/world/gen/settings/StructureSeparationSettings;)Lnet/minecraft/util/math/BlockPos; merged by com.performant.coremod.mixin.world.StructureMixin with priority 1000 [PREINJECT Applicator Phase -> sodium.mixins.json:gen.features.StructureFeatureMixin -> Prepare Injections ->  -> redirect$zop000$biomeConditionalGetChunk(Lnet/minecraft/world/IWorldReader;IILnet/minecraft/world/chunk/ChunkStatus;)Lnet/minecraft/world/chunk/IChunk; -> Prepare]
```

**Comment by spoorn** [comment]
Oh right, my bad I missed that.  This mod is **not** compatible with Performant. 

From a previous comment:

_Performant messes around with Mob AIs which breaks several other mods, such as Resourceful Bees, as one of the ways it improves performance.  However, they close sourced their code so no one can help debug it or fix it.  They seem to be willing to break other mods without any warnings or support.  As a result, other modders and I can't spend all our time trying to reverse engineer what Performant does, and constantly play catch up to be compatible with the mod, so the current expectation is compatibility between Performant and this mod will not be maintained._
