### ISSUE TITLE
Game crashes when pondering Create items while using Sodium

### ISSUE THREAD

**Issue by BinaryState0** [spoorn/sodium-forge#28]
Game crashes when viewing an item's ponder in create
1.- ponder an item
2.- crash

[crash-2021-06-18_15.48.28-client.txt](https://github.com/spoorn/sodium-forge/files/6679108/crash-2021-06-18_15.48.28-client.txt)

Mod List: 
		TRansliterationLib-1.0.4.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.4               |DONE      |NOSIGNATURE
		areas_1.16.5-2.2.jar                              |Areas                         |areas                         |2.2                 |DONE      |NOSIGNATURE
		mcw-windows-1.0.3-mc1.16.5.jar                    |Macaw's Windows               |mcwwindows                    |1.0.3               |DONE      |NOSIGNATURE
		villagernames_1.16.5-2.9.jar                      |Villager Names                |villagernames                 |2.9                 |DONE      |NOSIGNATURE
		TerraForged-1.16.5-0.2.10.jar                     |TerraForged                   |terraforged                   |0.2.10              |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		Controlling-7.0.0.23.jar                          |Controlling                   |controlling                   |7.0.0.23            |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.5.0.jar                          |Placebo                       |placebo                       |4.5.0               |DONE      |NOSIGNATURE
		citadel-1.7.1-1.16.5.jar                          |Citadel                       |citadel                       |1.7.1               |DONE      |NOSIGNATURE
		alexsmobs-1.10.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.10.1              |DONE      |NOSIGNATURE
		GatewaysToEternity-1.16.3-1.0.1.jar               |Gateways To Eternity          |gateways                      |1.0.1               |DONE      |NOSIGNATURE
		Bookshelf-1.16.5-10.1.11.jar                      |Bookshelf                     |bookshelf                     |10.1.11             |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Tips-1.16.5-4.0.7.jar                             |Tips                          |tips                          |4.0.7               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		toolleveling-1.16.5-1.2.3.jar                     |Tool Leveling                 |toolleveling                  |1.16.5 - 1.2.3      |DONE      |NOSIGNATURE
		guardvillagers-1.16.5.1.2.4.jar                   |Guard Villagers               |guardvillagers                |1.2.4               |DONE      |NOSIGNATURE
		Apotheosis-1.16.4-4.6.1.jar                       |Apotheosis                    |apotheosis                    |4.6.1               |DONE      |NOSIGNATURE
		mcw-doors-1.0.3-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.3               |DONE      |NOSIGNATURE
		mysticalchemy-0.0.7.jar                           |Mystic Alchemy                |mysticalchemy                 |0.0.6               |DONE      |NOSIGNATURE
		SnowRealMagic-1.16.4-2.5.7.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.5.7               |DONE      |NOSIGNATURE
		carryon-1.16.5-1.15.5.15.jar                      |Carry On                      |carryon                       |1.15.5.15           |DONE      |8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		JustEnoughResources-1.16.5-0.12.1.121.jar         |Just Enough Resources         |jeresources                   |0.12.1.121          |DONE      |NOSIGNATURE
		supplementaries-1.16.5-0.13.2.jar                 |Supplementaries               |supplementaries               |1.16.5-0.13.1       |DONE      |NOSIGNATURE
		repurposed_structures-1.16.5-2.7.5-forge.jar      |Repurposed Structures         |repurposed_structures         |1.16.5-2.7.5-forge  |DONE      |NOSIGNATURE
		netherportalspread_1.16.5-5.1.jar                 |Nether Portal Spread          |netherportalspread            |5.1                 |DONE      |NOSIGNATURE
		ironfurnaces-1.16.5-2.6.8.jar                     |Iron Furnaces                 |ironfurnaces                  |2.6.8               |DONE      |NOSIGNATURE
		mcw-trapdoors-1.0.2-mc1.16.5.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.2               |DONE      |NOSIGNATURE
		mcw-fences-1.0.0-mc1.16.5.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.0               |DONE      |NOSIGNATURE
		villagespawnpoint_1.16.5-1.5.jar                  |Village Spawn Point           |villagespawnpoint             |1.5                 |DONE      |NOSIGNATURE
		JustARaftMod-1.16.3-1.1.3.jar                     |Just A Raft Mod               |justaraftmod                  |1.1.3               |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |NOSIGNATURE
		RealisticSleep-1.16.4-1.2.0.58-universal.jar      |Realistic Sleep               |realisticsleep                |1.2.0.58            |DONE      |NOSIGNATURE
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                |DONE      |NOSIGNATURE
		levelhearts-1.16.2-2.2.0.jar                      |LevelHearts                   |levelhearts                   |2.2.0               |DONE      |NOSIGNATURE
		betteranimals-1.16.4-5.5.0.jar                    |Cyber's Better Animal Models  |betteranimals                 |5.5.0               |DONE      |NOSIGNATURE
		BetterThirdPerson-Forge-1.16.4-1.5.0.jar          |Better Third Person           |betterthirdperson             |1.5.0               |DONE      |NOSIGNATURE
		tombstone-1.16-6.4.3.jar                          |Corail Tombstone              |tombstone                     |6.4.3               |DONE      |NOSIGNATURE
		antiquewaystones-1.2.jar                          |Antique Waystones             |antiquewaystones              |1.2                 |DONE      |NOSIGNATURE
		campfire_overhaul-1.16.5-1.0.4.1.jar              |Campfire Overhaul             |campfire_overhaul             |1.0.4.1             |DONE      |NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |DONE      |NOSIGNATURE
		mcw-roofs-2.0.1-mc1.16.5-4.jar                    |Macaw's Roofs                 |mcwroofs                      |2.0.1               |DONE      |NOSIGNATURE
		Project_MMO-1.16.5-3.58.4.jar                     |Project MMO                   |pmmo                          |1.16.5-3.58.4       |DONE      |NOSIGNATURE
		architectury-1.17.22-forge.jar                    |Architectury                  |architectury                  |1.17.22             |DONE      |NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |DONE      |NOSIGNATURE
		betterwithminecolonies-1.16.4-1.16.17.jar         |Better With Minecolonies      |betterwithminecolonies        |1.16.4-1.16.17      |DONE      |NOSIGNATURE
		smallships-1.16.5-1.8.5.jar                       |Small Ships Mod               |smallships                    |1.8.5               |DONE      |NOSIGNATURE
		CustomStartingGear-1.16.4-2.0.2.1-universal.jar   |Custom Starter Gear           |customstartinggear            |2.0.2.1             |DONE      |NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta16.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta16|DONE      |NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta9.jar           |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta9  |DONE      |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.41.jar                  |GeckoLib                      |geckolib3                     |3.0.41              |DONE      |NOSIGNATURE
		randombonemealflowers_1.16.5-1.3.jar              |Random Bone Meal Flowers      |randombonemealflowers         |1.3                 |DONE      |NOSIGNATURE
		Kiwi-1.16.5-3.5.1.jar                             |Kiwi                          |kiwi                          |3.5.1               |DONE      |NOSIGNATURE
		TrashSlot_1.16.3-12.2.1.jar                       |TrashSlot                     |trashslot                     |12.2.1              |DONE      |NOSIGNATURE
		ftb-library-forge-1605.3.1-build.26.jar           |FTB Library                   |ftblibrary                    |1605.3.1-build.26   |DONE      |NOSIGNATURE
		ftb-teams-forge-1605.2.1-build.12.jar             |FTB Teams                     |ftbteams                      |1605.2.1-build.12   |DONE      |NOSIGNATURE
		Shrines-1.16.5-1.8.1.jar                          |Shrines                       |shrines                       |1.16.5-1.8.1        |DONE      |NOSIGNATURE
		jei-1.16.5-7.7.0.106.jar                          |Just Enough Items             |jei                           |7.7.0.106           |DONE      |NOSIGNATURE
		item-filters-1605.2.4-build.30-forge.jar          |Item Filters                  |itemfilters                   |1605.2.4-build.30   |DONE      |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		createchunkloading-0.1.0.jar                      |Create Chunkloading           |createchunkloading            |0.1.0               |DONE      |NOSIGNATURE
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|DONE      |NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |DONE      |NOSIGNATURE
		mcw-paintings-1.0.1-mc1.16.5.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.1               |DONE      |NOSIGNATURE
		Clumps-6.0.0.25.jar                               |Clumps                        |clumps                        |6.0.0.25            |DONE      |NOSIGNATURE
		comforts-forge-1.16.5-4.0.0.4.jar                 |Comforts                      |comforts                      |1.16.5-4.0.0.4      |DONE      |NOSIGNATURE
		NaturesCompass-1.16.5-1.9.0.jar                   |Nature's Compass              |naturescompass                |1.16.5-1.9.0        |DONE      |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |NOSIGNATURE
		configured-1.1.0-1.16.5.jar                       |Configured                    |configured                    |1.1.0               |DONE      |NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |DONE      |NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |DONE      |NOSIGNATURE
		additional_lights-1.16.4-2.1.3.jar                |Additional Lights             |additional_lights             |2.1.3               |DONE      |NOSIGNATURE
		iceandfire-2.1.7-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.7-1.16.5        |DONE      |NOSIGNATURE
		Toast-Control-1.16.4-4.3.1.jar                    |Toast Control                 |toastcontrol                  |4.3.1               |DONE      |NOSIGNATURE
		sodium-forge-2.1.7.jar                            |SodiumoPhosphoroLithium       |sodium                        |2.1.7               |DONE      |NOSIGNATURE
		firstaid-1.9.6.jar                                |First Aid                     |firstaid                      |1.9.6               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |DONE      |NOSIGNATURE
		dotcoinmod-1.16.jar                               |Dot Coin Mod                  |dotcoinmod                    |1.16 v5.3           |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		infernalmobs-1.16.2.1.jar                         |Infernal Mobs                 |infernalmobs                  |1.16.2.1            |DONE      |NOSIGNATURE
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |DONE      |NOSIGNATURE
		CraftingTweaks_1.16.5-12.2.1.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.1              |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.8.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.8               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |DONE      |NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |NOSIGNATURE
		nohostilesaroundcampfire_1.16.5-3.3.jar           |No Hostiles Around Campfire   |nohostilesaroundcampfire      |3.3                 |DONE      |NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |DONE      |NOSIGNATURE
		ftb-quests-forge-1605.3.2-build.18.jar            |FTB Quests                    |ftbquests                     |1605.3.2-build.18   |DONE      |NOSIGNATURE
		mana-and-artifice-1.3.0.6.jar                     |Mana and Artifice             |mana-and-artifice             |1.3.0.6             |DONE      |NOSIGNATURE
		ShoulderSurfing-1.16.5-2.0.6.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.5-2.0.6        |DONE      |NOSIGNATURE
		FirstPersonMod-2.0.1.jar                          |FirstPersonModel Mod          |firstpersonmod                |2.0.1               |DONE      |NOSIGNATURE
		villagertrades-0.3.jar                            |Villager Trades               |villagertrades                |0.3                 |DONE      |NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |NOSIGNATURE
		notenoughanimations-1.2.4.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.2.4               |DONE      |NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |DONE      |NOSIGNATURE
		diet-forge-1.16.5-0.33.jar                        |Diet                          |diet                          |1.16.5-0.33         |DONE      |NOSIGNATURE
		carrotslib-mc1.16.5-3.0b5.jar                     |Carrots Lib                   |carrots                       |3.0b5               |DONE      |NOSIGNATURE
		vanillafoodpantry-mc1.16.5-6.0b5.jar              |Vanilla Food Pantry           |vanillafoodpantry             |6.0b5               |DONE      |NOSIGNATURE
		polymorph-forge-1.16.5-0.25.jar                   |Polymorph                     |polymorph                     |1.16.5-0.25         |DONE      |NOSIGNATURE
		randomvillagenames_1.16.5-1.1.jar                 |Random Village Names          |randomvillagenames            |1.1                 |DONE      |NOSIGNATURE
		backpacked-1.10.1-1.16.3.jar                      |Backpacked                    |backpacked                    |1.10.1              |DONE      |NOSIGNATURE
		structurize-0.13.177-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.177-ALPHA      |DONE      |NOSIGNATURE
		minecolonies-0.14.221-BETA-universal.jar          |MineColonies                  |minecolonies                  |0.14.221-BETA       |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v3a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v3a          |DONE      |5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		valhelsia_core-16.0.9.jar                         |Valhelsia Core                |valhelsia_core                |16.0.9              |DONE      |NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.2.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.2        |DONE      |NOSIGNATURE
		healingcampfire_1.16.5-3.2.jar                    |Healing Campfire              |healingcampfire               |3.2                 |DONE      |NOSIGNATURE
		DynamicTreesTerraForged-1.16.5-1.0.0.jar          |Dynamic Trees for TerraForged |dtterraforged                 |1.16.5-1.0.0        |DONE      |NOSIGNATURE

**Comment by spoorn** [comment]
Update Sodium to 2.2+
