### ISSUE TITLE
TheEndBiomeSourceMixin Crash

### ISSUE THREAD

**Issue by WenXin20** [spoorn/sodium-forge#3]
### Reproduction Steps
The game crashed on startup, I suspected [Biomes You'll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3337158), [Simply Improved Terrain](https://www.curseforge.com/minecraft/mc-mods/simply-improved-terrain), or [Better End](https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port) may be involved as the log mentions `sodium.mixins.json:gen.fast_island_noise.TheEndBiomeSourceMixin failed injection check`. If none of those cause a crash, I can look into it more.

### Crash Report File
https://gist.github.com/WenXin20/8fad101f3b0cc49be4ef77961ab05f89#file-sodium_mixin_crash-txt-L283

**Comment by spoorn** [comment]
Compatibility issue with Simply Improved Terrain as they overwrite one of the methods here: https://github.com/KdotJPG/Simply-Improved-Terrain/blob/Forge-1.16/src/main/java/jpg/k/simplyimprovedterrain/mixin/MixinEndBiomeProvider.java#L41

**Comment by WenXin20** [comment]
Ah, thought that might be the one.
Is it up to that mod to add compat?

**Comment by spoorn** [comment]
Fixed in https://github.com/spoorn/sodium-forge/commit/1db9e4b9e5008ee71e76992e2341195014c65512

**Comment by WenXin20** [comment]
Thanks! Working great so far. :)
