### ISSUE TITLE
Water is invisible

### ISSUE THREAD

**Issue by Swifts12345** [spoorn/sodium-forge#31]
### Expected Behavior
_Water to be fully visible and be much like how it is in the vanilla game_

### Actual Behavior
_Water itself is still present but is completely invisible. You can still go inside it and your screen subsequently tints blue, and it still flows and breaks grass when flowing, but it itself isn't visible. You can still see shadows in large bodies of water such as in oceans._

### Reproduction Steps
1. Have Sodium Reforged enabled
2. Enter world
3. Water is invisible

### Attachments

With Sodium Reforged:
![2021-06-19_12 00 38](https://user-images.githubusercontent.com/65256110/122640632-86fb1200-d0f8-11eb-8788-4119f9f0c484.png)

Without Sodium Reforged:
![2021-06-19_12 02 44](https://user-images.githubusercontent.com/65256110/122640642-95e1c480-d0f8-11eb-809a-52d7dfa65c88.png)

### Mods list
[Adventure of a Lifetime-0.5.zip](https://github.com/spoorn/sodium-forge/files/6680578/Adventure.of.a.Lifetime-0.5.zip)

### System Information

- Java Version: [1.8.0_51 64 bit]
- CPU: [Intel core i5-9600k]
- GPU: [Nvidia Geforce GTX-1070 Ti]
- Sodium Reforged Version: [2.2]

**Comment by grayscale420** [comment]
If your graphics settings are set to fabulous, turn them down to either fancy or fast.

**Comment by Swifts12345** [comment]
Fixes #

**Comment by Swifts12345** [comment]
> If your graphics settings are set to fabulous, turn them down to either fancy or fast.

Got it, fixed now
