### ISSUE TITLE
Ars Nouveau mana jars not rendering correctly

### ISSUE THREAD

**Issue by jochuan** [spoorn/sodium-forge#36]
### Expected Behavior
Mana jars from Ars Nouveau should show liquid mana inside them but with sodium they became invisible as if they are empty

### Actual Behavior
You should be able to see liquid mana inside the jars

### Reproduction Steps
Install Ars Nouveau and Sodium then go on creative and place a creative mana jar or another half full mana jar

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.
![image](https://user-images.githubusercontent.com/11268912/122661504-6adf8b00-d161-11eb-9db5-48daffb24f7e.png)
In the right there is a full mana jar and on the left there is a empty jar
![image](https://user-images.githubusercontent.com/11268912/122661510-7f238800-d161-11eb-8615-d9f93d0744b0.png)
The two render as empty jars

### Mods list
Ars Nouveau and Sodium

### System Information
![image](https://user-images.githubusercontent.com/11268912/122661609-741d2780-d162-11eb-810e-db043332bdb7.png)

- Java Version: 8
- CPU: Ryzen 5 3500U
- GPU: Vega 8
- Sodium Reforged Version: 2.2

**Comment by jochuan** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/38
Maybe is the same bug ?

**Comment by spoorn** [comment]
Fixed in https://github.com/spoorn/sodium-forge/commit/ccd500719d838b4045de710cf5cfc8d0a91eaf39, will be in next release
