### ISSUE TITLE
AE2 ME drive render issue

### ISSUE THREAD

**Issue by MisterZam** [spoorn/sodium-forge#37]
The slot face is all black except for the drives' lit up texture

**Comment by MisterZam** [comment]
Also Block Carpentry Mod has xray issue with sodium installed

**Comment by spoorn** [comment]
any screenshots?

**Comment by frank89722** [comment]
> any screenshots?

![image](https://user-images.githubusercontent.com/10683361/127101955-27ae154e-9c5f-45b6-9f46-bb37dcd403b0.png)
