### ISSUE TITLE
Game freezes when in Twilight Forest

### ISSUE THREAD

**Issue by Swifts12345** [spoorn/sodium-forge#38]
### Reproduction Steps
When loading chunks in the Twilight Forest with Sodium Reforged installed the world eventually freezes. When trying to quit the world the game stays stuck on the save screen. Memory usage goes up exponentially too.

1. Load into and move around Twilight Forest
2. Run into chunks that won't generate
3. You'll notice no mobs move/can be hit, all commands cease function and the world has frozen

### Server/Client logs
[latest.log](https://github.com/spoorn/sodium-forge/files/6683028/latest.log)

### Mods list
Include the list of mods loaded when the problem occurred.  If you have a crash report file, it should contain the list of mods running when the crash occurred.
[Adventure of a Lifetime-0.5.2.zip](https://github.com/spoorn/sodium-forge/files/6683031/Adventure.of.a.Lifetime-0.5.2.zip)

**Comment by spoorn** [comment]
From the log, I see an error with some orecruncher lib, not sodium: https://github.com/OreCruncher/Environs/tree/master

Not sure which mod is adding that to your modpack but this looks unrelated to sodium
