### ISSUE TITLE
Invisible Snow Real Magic Plants

### ISSUE THREAD

**Issue by WenXin20** [spoorn/sodium-forge#4]
### Expected Behavior
- Plants placed in snow layers should render.
- This is with the [Snow Real Magic](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic) mod.

### Actual Behavior
- Plants placed within snow layers render invisible.

### Reproduction Steps

1. Place a snow layer.
2. Right-click it with a flower.
3. Flower renders invisible.

### Attachments
![2021-06-08_22 42 05](https://user-images.githubusercontent.com/12000593/121290225-e2810080-c8ab-11eb-9241-e711b314328e.png)

### System Information
![2021-06-08_22 51 13](https://user-images.githubusercontent.com/12000593/121290333-0cd2be00-c8ac-11eb-9b7a-688c720ec10e.png)

**Comment by spoorn** [comment]
I believe this is because the Snow Real Magic mod is mixing into a method that Sodium overwrites: https://github.com/Snownee/SnowRealMagic/blob/1.16/src/main/java/snownee/snow/mixin/MixinBlockRendererDispatcher.java

**Comment by spoorn** [comment]
You'll have to follow up with the Snow Real Magic mod owner for compatibility

**Comment by WenXin20** [comment]
Ah, thanks

**Comment by rafaelkai** [comment]
It seems that Snow Real Magic author doesn't know how to fix this, is there any way you can help him?
