### ISSUE TITLE
Mobs can't pathfind when using this mod

### ISSUE THREAD

**Issue by romeocutitarul** [spoorn/sodium-forge#40]
### Expected Behavior
Wither Skeletobs would pathfind to the whole in the ground and the zombified piglins would pathfind to the turtle eggs.

### Actual Behavior
Mobs just stopped pathfinding.

### Reproduction Steps
Mobs simply cannot pathfind, I will attach 2 videos down below.

### Attachments
I will add 2 videos that I uploaded to YouTube because they are too big to attach here: 
1) https://www.youtube.com/watch?v=LOpN-N5xbec
2) https://www.youtube.com/watch?v=jrJm3G-p08k

### [Optional] Server/Client logs
Sometimes a crash won't output a crash report file.  In your `logs/` folder, there should be a `latest.log` and/or `debug.log`.  You may include the **END** of this log showing any errors and a few surrounding lines of context.  Don't include the entire file as it may contain some information of your file system.  

### Mods list
I tried removing every mod in my modpack, but sodium is the only one that causes this bug.

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [1.8.0_51 64 bit]
- CPU: [AMD Ryzen 5 3600 ]
- GPU: [GTX 1050 TI OC]
- Sodium Reforged Version: [2.2]

**Comment by spoorn** [comment]
Most likely a bug with Lithium.  I'm considering removing Lithium altogether, or at least make it configurable via the config to enable/disable but have not had the time

**Comment by spoorn** [comment]
Disabled Lithium by default: https://github.com/spoorn/sodium-forge/commit/faa7fd806bcde35f8c8efa0ee4487e11ad85dfba
