### ISSUE TITLE
Rendering 

### ISSUE THREAD

**Issue by idkfordisco** [spoorn/sodium-forge#41]
### Expected Behavior
All blocks should render properly 

### Actual Behavior
Everything is flashing

### Reproduction Steps
1. Load in world
2. That's it

### Attachments
https://streamable.com/a4getk

### Mods list
Only this mod itself used

### System Information

- Java Version: Version 8 Update 291
- CPU: Intel(R) Core(TM) i5-8400T CPU @ 1.70 GHz
- GPU: Intel UHD 630
- Sodium Reforged Version: sodium-forge-2.2

**Comment by spoorn** [comment]
Could you try changing the renderer to 3.3 or 2.0?  In Video -> Advanced

**Comment by idkfordisco** [comment]
Ok so 3.3 and 2.2 fixed it thx :D

**Comment by spoorn** [comment]
@idkfordisco I'm guessing your GPU doesn't support Multidraw.  Maybe try updating your drivers if they've updated them to support it: https://downloadcenter.intel.com/product/126790/Intel-UHD-Graphics-630
