### ISSUE TITLE
Endergetic Expension: "Poise Trees"s top blocks not rendering.

### ISSUE THREAD

**Issue by Blunder-G** [spoorn/sodium-forge#42]
1 - Install Endergetic Expension and Sodium Reforged
2 - Go to the End
3 - /locatebiome endergeticexpension:poise_forest
4 - Look top of the trees.
5 - Delete Sodium Reforged and try again.

Versions: 

Endergetic Expension: Endergetic 1.16.4 - 3.0.0
Sodium Reforged: sodium-forge-2.2

**Comment by Inqie** [comment]
There might be another variable in your setup or it might be system specific, as I don't have this problem.

**Comment by Blunder-G** [comment]
> There might be another variable in your setup or it might be system specific, as I don't have this problem.

Are you sure they are the same versions? It's weird that it's from the computer. Perhaps one of the "Advanced Settings" that Sodium uses may be causing this problem. I'll test it.

**Comment by spoorn** [comment]
Is this still reproducible?

**Comment by Blunder-G** [comment]
Lates versions don't have that issue. CLOSED SIR
