### ISSUE TITLE
Crash with Create's Cogwheels

### ISSUE THREAD

**Issue by Blunder-G** [spoorn/sodium-forge#44]
Putting on a cogwheel will cause it to be kicked (crashed) directly from the **game** and the **launcher**.

Sodium Version: **sodium-forge-2.2**

Create Version: **Create 1.16.4+ v0.3.1c**

1 - Download Create and Sodium Reforged
2 - Join a world
3 - Put a small cogwheel (i didn't test other Create stuffs)
4 - Your game should be crashed

PS: As i said before it doesn't generate any crash reports since it also kicks me out of the launcher. Sorry for that bad new :l

**Comment by KatBoyKota** [comment]
I have a modpack with both create and sodium installed, and Minecraft crashes before it even finishes loading.
![image](https://user-images.githubusercontent.com/86386755/123180772-31e93400-d449-11eb-8733-ab024ce79aa7.png)
this is the message I get,
[crash-2021-06-23_17.33.38-fml.txt](https://github.com/spoorn/sodium-forge/files/6705359/crash-2021-06-23_17.33.38-fml.txt)

**Comment by spoorn** [comment]
The second crash is due to https://github.com/Creators-of-Create/Create/issues/1799

I'm not sure about the first one.  I tried placing a small cogwheel down and it doesn't crash for me.  Perhaps it's from another mod?

**Comment by KatBoyKota** [comment]
I didn't know about that bug, thank you

**Comment by Blunder-G** [comment]
> The second crash is due to [Creators-of-Create/Create#1799](https://github.com/Creators-of-Create/Create/issues/1799)
> 
> I'm not sure about the first one. I tried placing a small cogwheel down and it doesn't crash for me. Perhaps it's from another mod?

I'm 100% sure it's not from another mod. Just in case I installed Sodium and Create and tried it. What could be the reason or how can I fix it?

**Comment by spoorn** [comment]
Since I can't reproduce this on my end, could you give me any crash reports or logs?

**Comment by spoorn** [comment]
Please recomment if you can add some logs
