### ISSUE TITLE
Game freezes when joining a server

### ISSUE THREAD

**Issue by emanuele246gi** [spoorn/sodium-forge#45]
### Expected Behavior
I obviously expected to join and play properly.

### Actual Behavior
When I enter the world, the game freezes and stops working.

### Reproduction Steps
The first time happened when I passed on a chunk that was not loading, but the second time happened when I just joined the world.

1. Just enter a server or walk on a not loaded chunk.

### [Optional] Server/Client logs
Only if you ask me to put it

### Mods list
The CivilizationPack on CurseForge, I created it and this is the only new mod since the last update

### System Information

- Java Version: [1.8.0_291]
- CPU: [Intel Core i7]
- GPU: [GTX 1070]
- Sodium Reforged Version: [2.3]

**Comment by spoorn** [comment]
Need some crash reports or logs

**Comment by spoorn** [comment]
Please recomment if you can add some logs
