### ISSUE TITLE
Specific mixins causing crashes with Mohist

### ISSUE THREAD

**Issue by DaringShepard** [spoorn/sodium-forge#46]
### Reproduction Steps

1. Install Sodium Reforged to a [Mohist](https://mohistmc.com/download/) server (my current version is 1.16.5-672).
2. Server crashes on startup.

### Crash Report File
https://gist.github.com/DaringShepard/c01044a66b1329a161e32e3ab47d34e1
(Doesn't produce a full crash report, but the crash "error" is at the bottom.)

### Mods list
No mods (unless you consider the server software [Mohist](https://mohistmc.com/download/) to be a mod). Crash is reproducible when only Sodium Reforged is installed.

### Additional Information
Crash can be remedied by editing the soduim.mixins.json file and removing/commenting out certain mixins. [Here's my edited version to see the mixins which cause the crashes.](https://gist.github.com/DaringShepard/6385b40d38923d2f5f576d59986aeef6)

Removing the first erroring mixin will lead to a second, third, and so on. Each produce their own, unique, crashes:

1. No removed mixins - [alloc.chunk_random.ServerWorldMixin causes the crash.](https://gist.github.com/DaringShepard/fe9ce21b797cc8fc34819f2e92cef612)
2. **alloc.chunk_random.ServerWorldMixin** removed - [world.tick_scheduler.ServerWorldMixin causes the crash.](https://gist.github.com/DaringShepard/ec4138af13b5562f2dc86f42e77a6373)
3. Previous one and **world.tick_scheduler.ServerWorldMixin** removed - [alloc.chunk_ticking.ServerChunkManagerMixin causes the crash.](https://gist.github.com/DaringShepard/8e684e55bdb0a2b9715070381d39e3aa)
4. Previous two and **alloc.chunk_ticking.ServerChunkManagerMixin** removed - [chunk.count_oversized_blocks.ChunkSectionMixin causes the crash](https://gist.github.com/DaringShepard/f63acd66367f5b6fc154e6f33bb73b31) and produces [a crash report for the first time.](https://gist.github.com/DaringShepard/9b0269566a32bc86e3061f7fa3c73a7f)
5. Previous three and **chunk.count_oversized_blocks.ChunkSectionMixin** removed - server starts properly [and fully loads.](https://gist.github.com/DaringShepard/2bb2d94ff82cf088ca3f35841e531f2a)

**Comment by spoorn** [comment]
You'll probably need to follow up with them first.  I'm not sure what version of Forge they're using or if it's modified so that the mixins can't find the appropriate classes/methods to mixin to.
