### ISSUE TITLE
Game crashes after couple of seconds of loading

### ISSUE THREAD

**Issue by Kizwiz** [spoorn/sodium-forge#47]
I'm not sure why, but my game crashes a couple of seconds after loading a world. I asked for help from CurseForge community and they seem to think its Lithium. I wasn't sure if this was something you'd want to look into or not, if not then apologies for wasting your time.

Crash Report:
https://pastebin.com/CpT2mZ0E

**Comment by spoorn** [comment]
I plan to remove Lithium as it's causing too many issues that I don't have time to maintain and/or fix

**Comment by spoorn** [comment]
Lithium is removed by default now
