### ISSUE TITLE
Surface Turns Invisible

### ISSUE THREAD

**Issue by fleetag** [spoorn/sodium-forge#48]
Hi, I tried your mod to see if it could increase my modpack's framerate when entering a world. My test survival world looked fine at first, but when I started to turn my camera, the landscape around me started to turn invisible in and out.

### Attachments
![2021-06-24_20 33 17](https://user-images.githubusercontent.com/70476620/123352361-1fe0c180-d52d-11eb-8b72-b087d148f7d8.png)

![2021-06-24_20 43 54](https://user-images.githubusercontent.com/70476620/123352409-35ee8200-d52d-11eb-9b72-802d03ce58aa.png)

![2021-06-24_20 44 17](https://user-images.githubusercontent.com/70476620/123352428-3e46bd00-d52d-11eb-913d-5f0dda8dcf84.png)

### Mods list
- Abnormals Core
- Animated Recipe Book
- AutoRegLib
- Berry Good
- Better Spawner Control
- Buzzier Bees
- Collective
- Configured
- Enhanced Mushrooms (Forge)
- Extra Boats
- Forgery
- Quark
- Savage & Ravage
- Upgrade Aquatic
- V-Tweaks
- VanillaTweaks
- Well-Behaved Mobs
- YUNG's API (Forge)
- YUNG's Better Caves (Forge)
- YUNG's Better Mineshafts (Forge)

### System Information
- Java Version: 1.16.5
- CPU: Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
- Sodium Reforged Version: sodium-forge-2.3.jar

**Comment by spoorn** [comment]
What GPU do you have?  Could you try one of the OneShot renderers, 2.0 or 3.3.  Under Video Settings -> Advanced

**Comment by fleetag** [comment]
I don't have a GPU installed, but I was able to use both OneShot renderers and they are working correctly. Thank you for your help! Could you add this to your mods FAQ incase other people experience this same issue?
