### ISSUE TITLE
Make each mod toggleable

### ISSUE THREAD

**Issue by HyprGirl** [spoorn/sodium-forge#49]
I would like a config file with options to turn off sodium, lithium or phosphor separately.

I want to do this because I want to use optifine instead of sodium, but be able to keep lithium and phosphor.

**Comment by BugmanBugman** [comment]
I feel like this could be better done if it was split into 3, like Aeiou's forks

**Comment by R0M-A** [comment]
IDK, I find it annoying dealing with 20-ish performance mods. I like everything to be a simple 1 mod package and a config to turn parts on/off. I understand larger size and possibly longer load times, but a config would probably be easier to implement.

**Comment by ModernGamingWorld** [comment]
I agree keep it as One Mod and just add a config

**Comment by spoorn** [comment]
I'm stretched a bit thin for adding this.  For now, you can try disabling specific mixins in `sodium-mixins.properties`.  

These are all the options you can add: https://github.com/spoorn/sodium-forge/blob/a75b718bd86ca6b70538afbcd070d598d808ef36/src/main/java/me/jellysquid/mods/sodium/common/config/SodiumConfig.java#L26

**Comment by Blunder-G** [comment]
Agree with that idea, i prefer starlight to phospor but i can't switch the mods

**Comment by R0M-A** [comment]
Thanks! I'll try using mixins. Could you just update the link in the mixins.properties to this one?

![image](https://user-images.githubusercontent.com/86451288/123627965-e7820180-d812-11eb-9584-ad2ebb140073.png)

**Comment by masquerade908** [comment]
> Thanks! I'll try using mixins. Could you just update the link in the mixins.properties to this one?
> 
> ![image](https://user-images.githubusercontent.com/86451288/123627965-e7820180-d812-11eb-9584-ad2ebb140073.png)

So uh...any idea how to actually do this? I'm looking at the file but it looks so foreign to me so I have no idea how to disable Phosphor so I can use Starlight instead. Delete everything that has lighting in it or?

**Comment by R0M-A** [comment]
~~I'm pretty sure sodium-mixins.properties is only for Sodium mixins, I could be wrong though.~~
I was wrong. You can use it for sodium and lithium
Also, I recommend reading the https://github.com/spoorn/sodium-forge/issues/2 issue for more information.

**Comment by R0M-A** [comment]
After some testing, I've found that using `mixin.features = false` disables all of sodium, keeping lithium and phosphor. I can now use optifine in peace. Thank you and keep up the good work!

**Comment by spoorn** [comment]
Closing this as they are toggleable via the config file.  I'll consider separating the mods out later

**Comment by Pannoniae** [comment]
There is a starlight branch now which has Starlight instead of Phosphor.
