### ISSUE TITLE
Stained Glass is not translucent

### ISSUE THREAD

**Issue by WenXin20** [spoorn/sodium-forge#5]
### Expected Behavior
- Stained Glass should render translucent.

### Actual Behavior
- Stained Glass renders as transparent with fast or fancy graphics.
- Stained Glass renders completely invisible with fabulous graphics.

### Reproduction Steps
Provide information on how to reproduce this game crash. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear! If applicable, please provide a world file as a compressed ZIP which contains a minimally reproducible example of the issue. 

1. Place a Stained Glass block.
2. Observe.

### Attachments
![2021-06-08_22 48 03](https://user-images.githubusercontent.com/12000593/121290859-f37e4180-c8ac-11eb-8898-f5557b977a78.png)

### System Information
![2021-06-08_22 53 14](https://user-images.githubusercontent.com/12000593/121290880-fbd67c80-c8ac-11eb-99e3-59d3d84ca16b.png)

**Comment by spoorn** [comment]
Should be fixed in https://github.com/spoorn/sodium-forge/commit/4f288b03ea4c8fcddf64ff3410086cae9ad4d9b0

**Comment by WenXin20** [comment]
Thanks!
