### ISSUE TITLE
Game Crash On startup

### ISSUE THREAD

**Issue by potential1energy** [spoorn/sodium-forge#50]
I have No Idea why but every time I start my game It will just crash.
I don't know what mod is causing the problem and I would like to know.
Sodium Works by itself on the same forge version.

here is log because no crash report was generated
https://gist.github.com/potential1energy/aac0f90371271835b80ade1daed771bb

and mod list
https://gist.github.com/potential1energy/96a2932b6e327a87ac724b235b9446f0

**Comment by R0M-A** [comment]
You should read the compatibility section, it says:
> This mod is incompatible with Optifine, Performant, Immersive Portals

So you should remove Immersive Portals. I also suggest removing older versions of mods.

**Comment by spoorn** [comment]
That's a compatibility issue with SKDS Core mod: https://github.com/Sasai-Kudasai-BM/SKDS-Core/blob/main/src/main/java/net/skds/core/mixins/multithreading/ServerChunkProviderMixin.java#L44

https://www.curseforge.com/minecraft/mc-mods/skds-core

Sodium overwrites the method to do some important caching.  I'd follow up with the other mod for compatibility

**Comment by potential1energy** [comment]
I know this is closed but how exactly would I fix this, I'm not very familiar with this stuff
