### ISSUE TITLE
Latest versions of Sodium Reforged causes FPS drops

### ISSUE THREAD

**Issue by Blunder-G** [spoorn/sodium-forge#51]
Sodium 2.1.7 with 8 chunks: 40-60 FPS

Sodium 2.3.1 with 6 chunks: 0-20 FPS

Whatta heck?

**Comment by Blunder-G** [comment]
PS: In moded minecraft

**Comment by spoorn** [comment]
The major changes between those versions are 

1. Removed merging of Mipped passes with regular passes
2. Translucency sorting

I can't remove (1) as it will cause issues with cutout rendering and other things.  For (2), some optimizations are in the repo but not yet released.  Also planning to make it a configurable option in the menu

**Comment by spoorn** [comment]
Made translucency sorting configurable
