### ISSUE TITLE
Inspirations: Nether portals are crashing the game or render badly chunks next to the portal

### ISSUE THREAD

**Issue by lepeli** [spoorn/sodium-forge#52]
# Edit 28/06

The bug has been fixed in the version 2.4 

### Expected Behavior

The game shouldn't show invisible blocks nor crash and should show the portal.

### Actual Behavior

When a portal is placed the game sometimes crashes or show invisibles in the

The game crashes (freezes so badly that we need to restart it) or invisible blocks are showing.
It happens for the chunk next to the portal and the portal as well.

### Reproduction Steps

1. Create a nether portal
2. Lit the portal
3. The game should crash if it doesn't you can create a bigger portal or a normal one.

### Attachments

![2021-06-25_11 32 22](https://user-images.githubusercontent.com/24854702/123556413-66cbf280-d78b-11eb-9f07-cd93cfad4ae7.png)
![2021-06-25_11 51 34](https://user-images.githubusercontent.com/24854702/123556451-97139100-d78b-11eb-8ffd-963dbc0f3b4d.png)
![2021-06-25_11 33 21_2](https://user-images.githubusercontent.com/24854702/123556435-7e0ae000-d78b-11eb-8655-e00c0e21e7ba.png)
![2021-06-25_11 34 03](https://user-images.githubusercontent.com/24854702/123556440-86fbb180-d78b-11eb-92f8-7ba5f1bea2a9.png)
![2021-06-25_11 33 21](https://user-images.githubusercontent.com/24854702/123556429-73e8e180-d78b-11eb-98d4-71a58f322da9.png)

### [Optional] Server/Client logs

[latest.log](https://github.com/spoorn/sodium-forge/files/6722158/latest.log)
[debug.log](https://github.com/spoorn/sodium-forge/files/6722159/debug.log)

### Mods list
[mods.txt](https://github.com/spoorn/sodium-forge/files/6722162/mods.txt)
(Optifine is in the list but not loaded because of the extension's name)
### System Information

- Java Version: 1.8.0_51 64 bit
- CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 2592 MHz
- GPU: NVIDIA GeForce GTX 960M 2GB
- Sodium Reforged Version: 2.2-2.3.1

**Comment by R0M-A** [comment]
You should read the compatibility section, it says:
> This mod is incompatible with Optifine, Performant, Immersive Portals

So you should remove Optifine and try again.

**Comment by lepeli** [comment]
> You should read the compatibility section, it says:
> > This mod is incompatible with Optifine, Performant, Immersive Portals
> 
> So you should remove Optifine and try again.

Optifine isn't loaded in the game (I've changed the extension so Minecraft doesn't load it)

**Comment by spoorn** [comment]
Do you have the same problem with the Oneshot renderers 3.3 or 2.0?

If so, try updating your GPU drivers

**Comment by lepeli** [comment]
So I just updated to the last driver version for my graphic card and the issue is still there with both Oneshot renderers

![image](https://user-images.githubusercontent.com/24854702/123615078-40e33400-d805-11eb-8474-1fd47c514476.png)

**Comment by spoorn** [comment]
Damn, unfortunately I don't have any other leads on this right now.  You could try updating your Java - the minecraft default 1.8.0_51 has some bugs, but I doubt that's causing those rendering issues.  I don't have your GPU myself to test on

**Comment by spoorn** [comment]
Spoke too soon, I see there's an error at the end of your log.  Could you try removing https://www.curseforge.com/minecraft/mc-mods/inspirations to see if it fixes?

**Comment by lepeli** [comment]
Sure thing !

I've tried to use the latest java version and sadly it doesn't fix the bug.

I'm testing if removing inspirations fixes it.

**Comment by lepeli** [comment]
I've got an update, removing Mantle and Inspirations fixed it. 

Is there any way to still use both mods or should I remove inspirations ?

**Comment by spoorn** [comment]
I'll try releasing an updated version of Sodium tomorrow and you can test to see if it fixes the issue in your world, or you could try building it from source yourself

**Comment by lepeli** [comment]
Thanks a lot. I'm going to try to build the mod from the source so you can be updated faster

**Comment by lepeli** [comment]
So I just built the mod from the sources and now I'm getting this error at start.

[crash-2021-06-28_12.51.35-client.txt](https://github.com/spoorn/sodium-forge/files/6725699/crash-2021-06-28_12.51.35-client.txt)

I may have problably done something badly (i'm really not sure about this)

**Comment by spoorn** [comment]
That crash is due to Java versions being backwards incompatible, but it's an easy fix.   See https://github.com/lmdbjava/lmdbjava/issues/116 for more conversation around it.  Try the latest source

**Comment by lepeli** [comment]
@spoorn thanks a lot. I've managed to build it and it works now. The issue with inspirations is now fixed ! 

Have a nice day and thanks for all your work. 

I'm just going to edit the issue in case someone has the same bug as me, so that they can know how to fix it

**Comment by TheBenjaminMD** [comment]
Im playing and having the same issue. Im not a coder or something, I have no clue what Imbdjava means or how I need to solve it. Any chances I can get some help to fix that issue?
