### ISSUE TITLE
'random' game crash while exploring related to "World Slices".

### ISSUE THREAD

**Issue by Darkmega18** [spoorn/sodium-forge#56]
**_### Reproduction Steps and Additional Information_**
To provide you with reproduction steps, I'd have to provide you a modpack AND the save, so the situation lines up. By it doesn't happen exactly the same way each time.

But all I was doing was roaming around an area on the edge of a dense forest fighting pillagers in a dungeon based camp and eventually the game buckles, saves itself then crashes with the following files, twice in a row, but not immediately sequentially in the same spot: in two different places but around the general area.

The First time my player was spazzing out red due to a false death issue with health changes that occurred cause of an origin I was testing, but it hadn't recurred yet in the second crash so is probably unrelated.

Hadn't come across such a crash in previous versions, mind you my play had been in other dimensions other than overworld for a while due to other origin based testings.

**_### Crash Report File_**
[crash-2021-06-30_00.58.45-client.txt](https://github.com/spoorn/sodium-forge/files/6734411/crash-2021-06-30_00.58.45-client.txt)

[crash-2021-06-30_00.39.20-client.txt](https://github.com/spoorn/sodium-forge/files/6734412/crash-2021-06-30_00.39.20-client.txt)

**_### [Optional] Server/Client logs_**
all the ending of the client log contains is the crash report and some other debug stuff from carry on and some busted recipes in various mods that keep showing up. nothing else of difference.

**_### Mods list_**
list will be in the report it's a lot-ish... and you can browse the pack list it if you really want to be sent it, provided the issue can't be discerned from the report.

**Comment by spoorn** [comment]
Fixed in https://github.com/spoorn/sodium-forge/commit/c4ef3ff45114f26f57d7b2c021401324bb38293c

**Comment by Darkmega18** [comment]
roger-roger
