### ISSUE TITLE
The new versions of Sodium are still worse than before... 

### ISSUE THREAD

**Issue by Blunder-G** [spoorn/sodium-forge#57]
To be honest, version 2.5 is way better than version 2.3. But still 5 times worse than version 1.7...

Your fixes seem to have worked. Whenever I use version 1.7 I see weird black things but these bugs are not present in newer versions. But in the 1.7 version, 8 chunks can give me 60 FPS with 150 mods, while in these new versions it does not change even if I lower all the settings and take the chunks to 6, it's always between 0-30

Am I the only one experiencing this? Because no one else seems to care.

Edit: I'm sorry for not responding to the questions i wrote earlier. I have a lot of work these days.

**Comment by spoorn** [comment]
Did you try disabling Translucency sorting?

**Comment by spoorn** [comment]
The only new feature that deliberately sacrifices FPS for quality is translucency sorting which is now toggleable.  There's not much else I can do as of right now since I've tried to keep parity with the main Sodium repo.  I can work on optimizations myself in the future
