### ISSUE TITLE
Mods that add custom villager professions and workstations are not compatible with Sodium Reforged, despite those mods being included in Spoornpack.

### ISSUE THREAD

**Issue by samedifferent** [spoorn/sodium-forge#58]
### Expected Behavior
When playing with mods that add custom villager workstations and custom villager professions, those villagers should obviously accept their workstations.

### Actual Behavior
While using Sodium reforged and the mod **More Villagers** or **Charm Reforged** (and I assume any other mods that add villager professions), villagers will not accept the custom workstations. Both of those mods are included in the Spoornpack. I am the developer of More Villagers, and many users have been complaining about this strange incompatibility.

### Reproduction Steps
Use either More Villagers or Charm Reforged with Sodium Reforged installed. Place down one of the custom workstations from either of those mods. Spawn in a villager next to it. The villager will not accept the custom workstation. They will only accept Vanilla workstations. Also, More Villagers has its own creative tab with all of the workstations, so you will be able to easily find them through there when you test for this bug.

### Mods list
Situation 1: Only More Villagers with Sodium Reforged.
Situation 2: Only Charm Reforged with Sodium Reforged.
In both situations, villagers did not accept the custom workstations. 

### System Information
- Java Version: 1.16.5
- Many people have reported this bug to me on all different operating systems: Windows, Mac, and Linux. 
- Sodium Reforged Version: I have confirmed that this bug occurs on the latest version of Sodium Reforged, which is **sodium-forge-2.5**, but this problem has been happening for many weeks now.

**Comment by spoorn** [comment]
Could you help me check if this is related to Lithium?  Try adding `mixin.ai=false` in sodium-mixins.properties under config/ ?

**Comment by samedifferent** [comment]
That fixed it. Where do we go from here?

**Comment by spoorn** [comment]
This fork already included Lithium/Phosphor in it, but I want to remove/separate them out.  I'm planning to at least have to default to false as there are too many bugs currently with them, but I don't have the bandwidth to fix/maintain them nor enhance

For now, you'll have to disable it in the config

**Comment by rafaelkai** [comment]
this still happens in the lastest version
