### ISSUE TITLE
Crash when lighting nether portal

### ISSUE THREAD

**Issue by evanbones** [spoorn/sodium-forge#59]
### Reproduction Steps
1. Light a nether portal
2. The game crashes

### Crash Report File
https://pastebin.com/1prB0E0S

Doesn't affect my friends who aren't using Sodium

**Comment by spoorn** [comment]
What version of Sodium are you on?

**Comment by evanbones** [comment]
Sodium-Forge-2.5

**Comment by spoorn** [comment]
It's a compatibility issue with the mod Inspirations, but I thought I fixed it.  Could you try the latest version?

**Comment by evanbones** [comment]
Just tried 2.7, here's the crash report: 
https://pastebin.com/cwDp7wgu

**Comment by evanbones** [comment]
I can disable custom portal colors, which seems to fix it, so it's not a huge deal I suppose. Just thought I'd let you know, thanks!
