### ISSUE TITLE
Sodium Reforged Causing crash with Vampirism on ItemColors and BlockColors

### ISSUE THREAD

**Issue by yor42** [spoorn/sodium-forge#63]
### Reproduction Steps

1. Place sodium and Vampirism together in mods
2. launch the game
3. Game should crash with array index out of bound error

### Crash Report File
[BlockColors](https://pastebin.com/2RuzVDet)
[ItemColors](https://pastebin.com/1NAaaTF8)

### [Optional] Server/Client logs
[Latest.log](https://pastebin.com/1Gjkyped)

### Mods list
[Modlist](https://pastebin.com/CyW2MJkA)

**Comment by yor42** [comment]
please note that this crash doesnt always happen; sometimes it starts normally and works without issue.

**Comment by spoorn** [comment]
https://github.com/spoorn/sodium-forge/commit/701eb80dd1e46708a91a52960fb549d76ba3e2cf should fix this, if you want you can try to build from source to test it out or wait for next release on curseforge
