### ISSUE TITLE
Crash on startup: MixinBufferBuilder

### ISSUE THREAD

**Issue by yor42** [spoorn/sodium-forge#64]
### Reproduction Steps

1. Build Jar from current source
2. Launch the game
3. The game crashes with java.lang.NoSuchMethodError

### Crash Report File
[Pastebin](https://pastebin.com/983uVS4U)

### [Optional] Server/Client logs
[debug.log](https://pastebin.com/wEUj2CgN)

### Mods list
[modlist](https://pastebin.com/knCwGcd4)

### Additional Information
crash is happening on the jar I built from latest source.(after BlockColor/ItemColor Thread fix)
I'm not sure if this is sodium's issue or one of other mod's issue. if this is from other mod, I'm sorry for wasting your time.

**Comment by spoorn** [comment]
I believe this is an issue when you compile the code using a different JDK version than what you run it with.  https://github.com/spoorn/sodium-forge/commit/f25cd821429682cc79eb9f46d643134114704980 hopefully should fix this, please reopen or recomment if it doesn't
