### ISSUE TITLE
Villagers still don't accept modded proffesions

### ISSUE THREAD

**Issue by rafaelkai** [spoorn/sodium-forge#68]
Using the 2.9 version this still occurs.

Adding a space between the comments and the "mixin.ai = false" in the config file fixes it, like this:
https://imgur.com/a/7UaQmSQ
Instead of this (the way the config file generates in 2.9):
https://imgur.com/a/Dx9XRzm

My guess is that Lithium it's also still activated by default.

**Comment by spoorn** [comment]
It worked for me without a space in between the comments.  The parser doesn't care about new lines anyways.  I'm thinking something else went wrong either with the mods or your experiment as I can't reproduce this
