### ISSUE TITLE
Toggleable Phosphor

### ISSUE THREAD

**Issue by Blunder-G** [spoorn/sodium-forge#69]
Phosphor is a great mod. Quite useful for Chunks. But for me, Starlight is more handy. But since Phosphor and Starlight do the same job, they are incompatible and I cannot use Starlight because I cannot turn off Phosphor. Sad... 

With the 2.7 update, Lithium can be turned on and off. Maybe the same could work for Phosphor?

And I have to say you did an amazing job! Each update mod offers even better performance and stabilization! Thanks :)

**Comment by spoorn** [comment]
Would be helpful if you could give me logs showing what parts of Phosphor conflict with Starlight when you try to run both together

**Comment by ahdg6** [comment]
Starlight rewrited light enigne,Phosphor modified light enigne,that means they are totally incompetible,If we need to use Starlight the only way is turn off Phosphor.

**Comment by Blunder-G** [comment]
ahdg6 is true. Starlight already has a conflict with Fabric versions of Phosphor. It's impossible the use both of them.
