### ISSUE TITLE
Another crash with Simply Improved Terrain even after 2.1.3

### ISSUE THREAD

**Issue by lebagvondouche** [spoorn/sodium-forge#7]
### Reproduction Steps
Saw the update to 2.1.3 that would solve the issues but it still crashes for me.

1. Client is crashing with Simply Improved Terrain, Biomes o Plenty and Oh the Biomes You´ll Go.

### Crash Report File
https://gist.github.com/haeihaiehaei/0dcdd081ad2f8ff18557d7f4d351c73a

**Comment by spoorn** [comment]
Should be fixed with https://github.com/spoorn/sodium-forge/commit/45efb40b925f4ffd8f28598c164bdacdda573d1e

**Comment by lebagvondouche** [comment]
Thanks buddy!
