### ISSUE TITLE
I accidentally closed the problem: Toggleble Phosphor

### ISSUE THREAD

**Issue by Blunder-G** [spoorn/sodium-forge#72]
Phosphor is a great mod. Quite useful for Chunks. But for me, Starlight is more handy. But since Phosphor and Starlight do the same job, they are incompatible and I cannot use Starlight because I cannot turn off Phosphor. Sad...

With the 2.7 update, Lithium can be turned on and off. Maybe the same could work for Phosphor?

And I have to say you did an amazing job! Each update mod offers even better performance and stabilization! Thanks :)

PS: It's impossible the use both of them. Starlight actually a Fabric mod that has a Forge port too and Fabric version of Starlight incompatible with Fabric version of Phosphor.

**Comment by BlueAmulet** [comment]
You could have just reopened the previous issue instead of making a new one.

But I'd also like to see a toggle for phosphor, starlight also works better for me.

**Comment by BugmanBugman** [comment]
I agree

**Comment by spoorn** [comment]
What happens if you run starlight together with Phosphor?  I ran both and saw no conflicts

**Comment by Blunder-G** [comment]
Wait, that's illegal! It's literally imposible to run both of them. THEY ARE THE SAME THINGS. How can they work together? HOW

**Comment by spoorn** [comment]
Phosphor doesn't overwrite the lighting engine.  Could be its Mixin injects play nicely and doesn't conflict with Starlight's overwrite of the lighting engine

**Comment by Blunder-G** [comment]
I tink they are working fine. Strange...
