### ISSUE TITLE
Worldgen is different from vanilla

### ISSUE THREAD

**Issue by skydark** [spoorn/sodium-forge#8]
### Expected Behavior

Vanilla worldgen of seed `3553695462283527100` near spawn (183, -56)
[Imgur](https://imgur.com/w2JjDW6)

### Actual Behavior

Add sodium-forge, worldgen of the same seed near spawn (-168, -21):
[Imgur](https://imgur.com/ygwYX4i)

Worldgen of the same seed near (183, -56):

[Imgur](https://imgur.com/3QkqTKW)

### Reproduction Steps

Add `sodium-forge (2.1.3)` to minecraft with only forge.

### System Information

- Java Version: [AdoptOpenJDK 14.0.2 64bit]
- CPU: [AMD Ryzen 7 5800X]
- GPU: [NVIDIA GeForce RTX 3070]
- Forge: [36.1.30]

### Thanks

Very impressive performance! Much smoother comparing to optifine when flying over the world. The only thing I am missing is the worldgen (that can be previewed by seed tools) and shaders. Many thanks to your great works!

**Comment by spoorn** [comment]
Try adding `mixin.gen.fast_layer_sampling=false` to sodium-mixins.properties
