### ISSUE TITLE
Twilight Forest freezes still happening despite suggested fixes

### ISSUE THREAD

**Issue by Swifts12345** [spoorn/sodium-forge#83]
### Reproduction Steps

1. Load up Twilight Forest latest build with Sodium Reforged installed
2. Walk/Fly around
3. The game freeezes

### Crash Report File
[New Paste 1.txt](https://github.com/spoorn/sodium-forge/files/6797573/New.Paste.1.txt)

### Additional Information
I have tried multiple times to find a fix yet it just isn't having it. Every time there seems to be some bug where it calls some random unrelated mod and I have no clue what's going on.

**Comment by spoorn** [comment]
I don't have much to work with with that log, are you sure it's due to sodium?  i.e. Does this happen with only Twilight Forest and Sodium installed?  Also try out the latest versions for both mods again

**Comment by yezhiyi9670** [comment]
Have you tried adding `mixin.chunk=false` to `sodium-mixins.properties`?

**Comment by Swifts12345** [comment]
I just did and it fixed it. As far as I'm aware the issue is completely gone. Thank you for the help.
