### ISSUE TITLE
Sodium and Eidolon Compatibility issue (render crash) 

### ISSUE THREAD

**Issue by Elfinlocks** [spoorn/sodium-forge#84]
### Reproduction Steps
Install Sodium Reforged, Install Eidolon. Place a crucible over a fire, and fill with water. The bubbling effect causes a client side render crash. Removing Sodium allows the client to render the bubbling effect without issue. This occurs with the latest versions of both mods (Eidolon 0.2.7 and Sodium Reforged 2.9.1)

**Comment by Pannoniae** [comment]
Can you please provide a crash report?^^

**Comment by Elfinlocks** [comment]
It didn't provide an actual crash report, but here's my latest and debug logs, which show the issue.
[latest.log](https://github.com/spoorn/sodium-forge/files/6804892/latest.log)
[debug.log](https://github.com/spoorn/sodium-forge/files/6804893/debug.log)

**Comment by Ritzumi** [comment]
I also got this crash as well. There is a workaround by changing particle quality to low. This will remove bubbling effect though.

**Comment by ghost** [comment]
going into eidolon-client.toml and disabling betterLayering config option seems to avoid the crash. although i didn't test how much that would impact the visuals of the mod yet.
