### ISSUE TITLE
Incompatibility with More Villagers mod

### ISSUE THREAD

**Issue by Explode007** [spoorn/sodium-forge#85]
The more villagers mod should work. I Should be able to place down the work tables and the villagers should take their desired professions

Instead, nothing happens, they just wander around ignoring the work station.

1) load up more villagers and sodium forge
2) spawn a villager and place a workstation from the more villagers mod
3) notice its not working as intended because he wont take the profession

### Mods list

Sodium reforged
More villagers

- Java Version: [1.8.0_51 64 bit]
- CPU: [Ryzen 3600x]
- GPU: [Radeon 5700XT]
- Sodium Reforged Version: [2.9.1]

**Comment by spoorn** [comment]
do you have 'mixin.ai=false' in your sodium-mixins.properties file under config/?

**Comment by Explode007** [comment]
Yep

**Comment by spoorn** [comment]
Could you take a gif/vid of it happening?  I can't reproduce this since the fix to disable Lithium, and have not had any more reports of the issue
