### ISSUE TITLE
Mixin Crash w/ Simply Improved Terrain

### ISSUE THREAD

**Issue by WenXin20** [spoorn/sodium-forge#9]
### Reproduction Steps
v2.1.2 worked great, but after updating to v2.1.3 and v2.1.4, the game crashes with Simply Improved Terrain again.
It is unable to find the class `jpg.k.simplyimprovedterrain.mixin.MixinEndBiomeProvider`

### Crash Report File
https://gist.github.com/WenXin20/63a907e21f5ea5e3382f988adba866e1

**Comment by spoorn** [comment]
Should be fixed with https://github.com/spoorn/sodium-forge/commit/45efb40b925f4ffd8f28598c164bdacdda573d1e
