### ISSUE TITLE
Exit Code: 0

### ISSUE THREAD

**Issue by Jeersy** [spoorn/sodium-forge#94]
Im trying to play the better minecraft modpack for 1.16.5 (Forge). I tried to put reforged sodium in it, but when i start the game, it crashes saying 'Exit code: 0". How can I fix this? If I turn off sodium it starts normally tho, so obv the problem is that.

**Comment by jclendineng** [comment]
Disable performant, it hooks into something sodium also hooks into so its 1 or the other, they are NOT compatible together

**Comment by spoorn** [comment]
Please reopen if disabling performant doesn't fix this
