### ISSUE TITLE
Going to the Nether

### ISSUE THREAD

**Issue by Victor-Noli** [spoorn/sodium-forge#95]
### Reproduction steps

1. Built a nether portal
2. Went through it
3. The game crashes

### Crash Report File
https://pastebin.com/HApyVf1v

### Mods list
https://www.curseforge.com/minecraft/modpacks/chroma-technology-2/relations/dependencies.

**Comment by spoorn** [comment]
I can't reproduce this on the latest version of the modpack.  The crash report says it's using sodium 2.9.2 which is an outdated version.  Please try to update to the latest versions

**Comment by spoorn** [comment]
see https://github.com/spoorn/sodium-forge/issues/91
