### ISSUE TITLE
Crashes with BetterFoliage.

### ISSUE THREAD

**Issue by MagmaSlime123** [spoorn/sodium-forge#96]
### Expected Behavior
The game loading.

### Actual Behavior
Title.

### Reproduction Steps
Add BetterFoliage with Sodium Reforged to your mods folder then start the game as per usual.

### Attachments
[crash-2021-07-20_14.04.51-fml.txt](https://github.com/spoorn/sodium-forge/files/6851064/crash-2021-07-20_14.04.51-fml.txt)

### Mods list
Had quite a few mods when getting this crash, but I just tried BetterFoliage and this mod afterwards. Same crash occurred.

### System Information
![2021-07-20_14 34 56](https://user-images.githubusercontent.com/51277766/126391591-2d90ce50-48f1-45a6-bf6b-c8334b1df3e1.png)

- Java Version: F3 debug above.
- CPU: F3 debug above.
- GPU: F3 debug above.

- Sodium Reforged Version: sodium-forge-2.9.4+rev.e07d46c.

**Comment by spoorn** [comment]
The crash report you sent is an error in Quark O Plenty vs Abnormals.  Also, there is already an issue with compatibility with Better Foliage: https://github.com/spoorn/sodium-forge/issues/16
