### ISSUE TITLE
when I open it with other mods it crashes.

### ISSUE THREAD

**Issue by legobatmanza** [spoorn/sodium-forge#97]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Place a Redstone Lamp beside a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. The game crashes

### Crash Report File
Please upload your crash report as a file to [GitHub Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and replace this text with a link to the uploaded report.

### [Optional] Server/Client logs
Sometimes a crash won't output a crash report file.  In your `logs/` folder, there should be a `latest.log` and/or `debug.log`.  You may include the **END** of this log showing any errors and a few surrounding lines of context.  Don't include the entire file as the first few lines of the log may contain some information of your file system. 

### Mods list
Include the list of mods loaded when the problem occurred.  If you have a crash report file, it should contain the list of mods running when the crash occurred.  

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.

**Comment by spoorn** [comment]
No information on what this crash is, please fill in the template, not copy and paste it

**Comment by spoorn** [comment]
Please reopen once you've provided the necessary information to debug

**Comment by legobatmanza** [comment]
I will later this week I’m sick :(

**Comment by legobatmanza** [comment]
can you send me the template please?

**Comment by legobatmanza** [comment]
nvm i found it
im just stupid

**Comment by legobatmanza** [comment]
Hello i can not put the ZIP file in the report thing is there anyway else I
can send it?

**Comment by Pannoniae** [comment]
You can upload the logs to pastebin or other sites:)

**Comment by legobatmanza** [comment]
thx

**Comment by legobatmanza** [comment]
can i use dropbox?

**Comment by Pannoniae** [comment]
Yup

**Comment by legobatmanza** [comment]
hey when i had Chlorine installed it didn't show any crash reports in the
crash report folder and when I did have chlorine in the mods folder it did
so that's another bug maybe

**Comment by legobatmanza** [comment]
or they just go in a different place

**Comment by legobatmanza** [comment]
it was a different crash report

**Comment by Pannoniae** [comment]
Don't install Chlorine and this at once, please. It won't work.

**Comment by legobatmanza** [comment]
I'm sorry but I don't understand what you mean.

**Comment by legobatmanza** [comment]
im sorry if i made you angry

**Comment by spoorn** [comment]
You can't use both Sodium and Chlorine together.  They are both rewriting the rendering pipeline in different ways so by nature they will conflict

**Comment by legobatmanza** [comment]
Ok thx for the info but isn’t sodium for fabric

**Comment by Pannoniae** [comment]
No, this is the forge port. It's unofficial, please don't go to the official discord for support

**Comment by legobatmanza** [comment]
I won’t and I know it is
