### ISSUE TITLE
Crash with Physics Mod

### ISSUE THREAD

**Issue by GeorgeOrwell1** [spoorn/sodium-forge#99]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Install Sodium Reforged v. 2.9.4 as well as v. 1.3.4 of [Physics Mod.](https://www.curseforge.com/minecraft/mc-mods/physics-mod)
2. Put the mods in the mods folder, and start the game.
3. During mod loading, Minecraft will crash.
4. Cry in agony.

###  Server/Client logs
Sometimes a crash won't output a crash report file.  In your `logs/` folder, there should be a `latest.log` and/or `debug.log`.  You may include the **END** of this log showing any errors and a few surrounding lines of context.  Don't include the entire file as the first few lines of the log may contain some information of your file system. 
[Pastebin of log.](https://pastebin.com/hHE0ZAap)
### Mods list
Include the list of mods loaded when the problem occurred.  If you have a crash report file, it should contain the list of mods running when the crash occurred.  

**physics-mod-1.3.4_forge**
**sodium-forge-2.9.4**

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.
(Using Forge 36.2.0)

**Comment by Pannoniae** [comment]
The log doesn't include the exception, it just contains a message about not being able to connect to the update server. Please provide the full log.^^

**Comment by GeorgeOrwell1** [comment]
[latest.log](https://github.com/spoorn/sodium-forge/files/6865090/latest.log)

**Comment by Pannoniae** [comment]
No error there

**Comment by GeorgeOrwell1** [comment]
Well I guess the issue isn't visible in the logs then.

**Comment by GeorgeOrwell1** [comment]
Fixed in the latest release thanks man.
